Feature/hero
SoftRyzen-internship/IM-CONSULTING pull request #10
Opened 2023-09-03 15:45 UTC by sergio-nezhigay

hero section draft, font weights add

2023-09-03 18:19 UTC, BogdanGlazkov requested changes

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +import HeroImg from '../../../public/images/hero-1250.png';
У нас у jsconfig.json встановлені alias, тому шлях можна починати просто з public/

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +import HeroImg from '../../../public/images/hero-1250.png';
Відокремити відступом зовнішні імпорти від внутрішніх

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +          Не чекай успіху - створи його разом з нами
Текст не хардкодимо, все беремо з data.json

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +        <div className="flex flex-col text-bgColor text-[8px] md:text-base leading-[17px] md:leading-[40px] xl:leading-[24px] -tracking-[0.01em]">
Чи потрібно задавати leading (line-height) для 1 строки?

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +      <div className="flex justify-between tracking-[-0.04em] mb-[26px] md:mb-[62px] xl:mb-[232px]">
-0.04em це в межах похибки, менше пікселя. Такі дрібні значення задавати не обов'язково

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +        <div className="flex flex-col text-bgColor text-[8px] md:text-base leading-[17px] md:leading-[40px] xl:leading-[24px] -tracking-[0.01em]">
0.01em - це в межах похибки, менше пікселя. Такі дрібні значення задавати не обов'язково

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +        <p className="flex flex-col text-[8px] md:text-base md:leading-[16px] xl:leading-[24px] -tracking-[0.01em] text-right">
0.01em - це в межах похибки, менше пікселя. Такі дрібні значення задавати не обов'язково

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +        />
Усі теги Image мають містити атрибут quality={100} (вимога техліда)

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +    <section className="relative h-auto pt-[74px] md:pt-[120px] xl:pt-[168px] overflow-hidden">
Додати id hero (для навігації)

2023-09-03 18:19 UTC, BogdanGlazkov commented on src/app/layout.jsx
> +  ],
Супер, дякую)

2023-09-04 06:34 UTC, sergio-nezhigay commented
thank you for comments!

2023-09-04 06:58 UTC, BogdanGlazkov requested changes

2023-09-04 06:58 UTC, BogdanGlazkov commented on jsconfig.json
> +      "data/*": ["./data/*"]
Перенеси будь-ласка папку data в src

2023-09-04 06:58 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +import { hero } from '@/data/data.json';
Вибиває попередження Should not import the named export 'hero' (imported as 'hero') from default-exporting module (only default export is available soon).
Імпортуємо data, а нижче у коді вже можна його деструктуризувати

2023-09-04 06:58 UTC, BogdanGlazkov commented on src/components/HeroContent/HeroContent.jsx
> +          <p className="max-w-[92px] md:max-w-[186px] ">{stat2Text}</p>
Розширити max-w, щоб текст вміщувався у одну строку

2023-09-04 07:26 UTC, BogdanGlazkov approved these changes

2023-09-04 07:41 UTC, merged