feature/about-company
SoftRyzen-internship/IM-CONSULTING pull request #14
Opened 2023-09-04 14:57 UTC by Anastasia-front

made adaptive block layout

all changes are meaningful, only one file Header.jsx with empty changes 
(for some reason, formatting changed the file, but it remained the same even in terms of formatting)

2023-09-04 16:12 UTC, nadiakhoptiuk requested changes

2023-09-04 16:12 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +      className={`text-font20 md:text-font24 xl:text-font36 font-light
краще маржини не використовувати для псевдоелементів

relative text-font20 md:text-font24 xl:text-font36 font-light
  before:content-['['] before:absolute before:left-[-25px] xl:before:left-[-29px] before:text-accent
  after:content-[']'] after:absolute after:right-[-25px] xl:after:right-[-29px] after:text-accent
  
  так наче точніше і добре центрується

2023-09-04 16:12 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +  className: PropTypes.string,
якщо цей пропс необовязковий, то якщо його не передадуть, в клас буде додаватись undefined.
додай дефолтний пустий рядок

2023-09-04 16:12 UTC, nadiakhoptiuk commented on src/sections/AboutCompany/AboutCompany.jsx
> +        <div className="flex flex-col gap-[48px] xl:gap-[120px]">
думаю, потрібно додати прихований заголовок h2 Про компанію (з json)

2023-09-04 16:12 UTC, nadiakhoptiuk commented on src/components/AboutCompanyHeading/AboutCompanyHeading.jsx
> +  className: PropTypes.string,
той самий нюанс, що вище писала
className= ""

2023-09-04 16:12 UTC, nadiakhoptiuk commented on src/components/AboutCompanyParagraph/AboutCompanyParagraph.jsx
> +  className,
className= ""

2023-09-04 16:12 UTC, nadiakhoptiuk commented on src/components/AboutCompanySecondBlock/AboutCompanySecondBlock.jsx
> +  const text = data.about.secondBlock;
можна в папці data створити папку home і там файли секцій, наприклад сюди будеш імпортувати файл about

2023-09-04 16:14 UTC, nadiakhoptiuk requested changes

2023-09-04 16:14 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +export const Title = ({ children, className }) => {
в ідеалі передавати тег пропсом, який може бути h2, h3, h4, p і також прокинути пропс, в залежності від якого задавати різні стилі (як у секції Процесу)
але поспілкуйтесь із тим, хто її робить, що ти це зробиш

2023-09-05 10:51 UTC, nadiakhoptiuk requested changes

2023-09-05 10:51 UTC, nadiakhoptiuk commented on src/data/data.json
> +            "Знайти рішення та мотивацію",
https://prnt.sc/rS5oZ1Er7J7c

2023-09-05 11:00 UTC, Anastasia-front commented on src/components/Title/Title.jsx
> +  className: PropTypes.string,
виправила

2023-09-05 11:01 UTC, Anastasia-front commented on src/sections/AboutCompany/AboutCompany.jsx
> +        <div className="flex flex-col gap-[48px] xl:gap-[120px]">
додала

2023-09-05 11:04 UTC, Anastasia-front commented on src/components/AboutCompanyHeading/AboutCompanyHeading.jsx
> +  className: PropTypes.string,
виправила

2023-09-05 11:04 UTC, Anastasia-front commented on src/components/AboutCompanyParagraph/AboutCompanyParagraph.jsx
> +  className,
виправила

2023-09-05 11:09 UTC, Anastasia-front commented on src/components/AboutCompanySecondBlock/AboutCompanySecondBlock.jsx
> +  const text = data.about.secondBlock;
виправила

2023-09-05 14:40 UTC, Anastasia-front commented on src/components/Title/Title.jsx
> +      className={`text-font20 md:text-font24 xl:text-font36 font-light
тут ці дужки виходять із контейнера, бо сам текст розтягується на всю його ширину
і вони не правильно розміщуються (коли 2 рядки, дужка відступає від всього блоку тексту і не по макету виходить)
<img width="544" alt="image" src="https://github.com/SoftRyzen-internship/IM-CONSULTING/assets/115567693/451d1446-dd9b-4a5f-a724-4a4e1280fab3">

2023-09-05 14:42 UTC, Anastasia-front commented on src/components/Title/Title.jsx
> +      className={`text-font20 md:text-font24 xl:text-font36 font-light
з відступами все правильно виглядає і розміщується відносно контейнера
інакше треба задавати фіксовану ширину тексту, але дужка в другому рядку все одно буде з самого краю

2023-09-05 14:44 UTC, Anastasia-front commented on src/data/data.json
> +            "Знайти рішення та мотивацію",
дякую, перевіряла й все одно пропустила

2023-09-05 15:51 UTC, Anastasia-front commented on src/components/Title/Title.jsx
> +export const Title = ({ children, className }) => {
чи можна зробити отак щоб стилі швидше у компоненті з tailwindcss прописати?

бо виходить ми й змінні з tailwind.config не зможемо використовувати й взагалі через адаптив буде буде багато коду на чистому css

<img width="522" alt="image" src="https://github.com/SoftRyzen-internship/IM-CONSULTING/assets/115567693/45df364c-8855-4604-9231-5f749cf9b43c">
<img width="358" alt="image" src="https://github.com/SoftRyzen-internship/IM-CONSULTING/assets/115567693/9091fb01-7566-4664-89ff-f7550fc02bc8">

2023-09-06 08:55 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +      className={`text-font20 md:text-font24 xl:text-font36 font-light
ці марджини це не ок, 
з початковими стилями не однакові відступи і не центрує вірно.., 
може краще уже просто додати спани і пробіли

або якщо підбереш маржини, щоб було однаково,  то вже залишимо їх - щоб ось так було, бо там десь є по 2 маржини:

https://prnt.sc/8l4vZG4duCxp

2023-09-06 09:04 UTC, nadiakhoptiuk commented on src/sections/AboutCompany/AboutCompany.jsx
> +        <div className="flex flex-col gap-[48px] xl:gap-[120px]">
треба не hidden, а клас visually-hidden створити в global

2023-09-06 09:07 UTC, nadiakhoptiuk commented on src/components/AboutCompanySecondBlock/AboutCompanySecondBlock.jsx
> +  const text = data.about.secondBlock;
я мала на увазі всі дані з секції винести в папку у файл about, з data прибрати

2023-09-06 09:08 UTC, nadiakhoptiuk commented on src/components/Title/Title.jsx
> +      className={`text-font20 md:text-font24 xl:text-font36 font-light
давай правильно перевір марджини, бо їх там є десь по 2, і щоб були однакові, і нехай уже будуть)

2023-09-06 11:39 UTC, Anastasia-front commented on src/components/Title/Title.jsx
> +      className={`text-font20 md:text-font24 xl:text-font36 font-light
виправила на паддінги, тепер все як на фото

2023-09-06 11:43 UTC, Anastasia-front commented on src/sections/AboutCompany/AboutCompany.jsx
> +        <div className="flex flex-col gap-[48px] xl:gap-[120px]">
виправила

2023-09-06 11:44 UTC, Anastasia-front commented on src/components/AboutCompanySecondBlock/AboutCompanySecondBlock.jsx
> +  const text = data.about.secondBlock;
тепер зрозуміла, переробила

2023-09-06 14:38 UTC, nadiakhoptiuk approved these changes

2023-09-06 14:40 UTC, merged