Fix/hero
SoftRyzen-internship/IM-CONSULTING pull request #15
Opened 2023-09-04 17:29 UTC by sergio-nezhigay

2023-09-04 20:53 UTC, BogdanGlazkov approved these changes

2023-09-05 06:57 UTC, nadiakhoptiuk requested changes

2023-09-05 06:57 UTC, nadiakhoptiuk commented on src/components/HeroContent/HeroContent.jsx
> +      <div className="h-[235px] md:h-[403px] xl:h-[659px] w-[223px] md:w-[381px] xl:w-[625px] absolute bottom-[-7px] md:bottom-[-12px] xl:bottom-[-17px] left-1/2 md:left-[43%] xl:left-[52%] transform
тут треба дещо змінити, для мобілки max-md:w-[62%], щоб фото збільшувалося в залежності від ширини екрану.
тому фіксовану ширину і висоту можна прибрати, висота auto
по ідеї ось так замінити:

h-auto md:h-[403px] xl:h-[659px] max-md:w-[62%]  md:w-[381px] xl:w-[625px] absolute bottom-[-7px] md:bottom-[-12px] xl:bottom-[-17px] left-1/2 md:left-[43%] xl:left-[52%] transform translate-x-[-50%] z-10 object-cover

2023-09-05 06:57 UTC, nadiakhoptiuk commented on src/components/HeroContent/HeroContent.jsx
> +          <span className="text-[12px] md:text-[28px] xl:text-[32px] font-medium leading-[13px] md:leading-[28px]  xl:leading-[32px] tracking-[0.1em]">
тут трошки жирність не відповідає макету (вигляд)
там здається, ти десь в минулому пр додавав налаштування

2023-09-05 06:57 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +    <section id="hero" className="hero-bgcolor relative h-auto overflow-hidden">
тут ід не буде взагалі, скоріш за все. цей момент ще подумаємо, якщо давати ід на героя, то хедер не буде видно при скролі вверх (на клік Головна)

2023-09-05 07:05 UTC, nadiakhoptiuk requested changes

2023-09-05 07:05 UTC, nadiakhoptiuk commented on src/components/HeroContent/HeroContent.jsx
> +    <div className=" h-[270px] md:h-[450px] xl:h-[539px]">
спробуй позбутись цього діва, задавши висоту на герой

2023-09-05 07:56 UTC, sergio-nezhigay commented on src/components/HeroContent/HeroContent.jsx
> +      <div className="h-[235px] md:h-[403px] xl:h-[659px] w-[223px] md:w-[381px] xl:w-[625px] absolute bottom-[-7px] md:bottom-[-12px] xl:bottom-[-17px] left-1/2 md:left-[43%] xl:left-[52%] transform
дякую, сорі за помилку

2023-09-05 07:57 UTC, sergio-nezhigay commented on src/components/HeroContent/HeroContent.jsx
> +          <span className="text-[12px] md:text-[28px] xl:text-[32px] font-medium leading-[13px] md:leading-[28px]  xl:leading-[32px] tracking-[0.1em]">
так, десь загубились настройки фонтів. засунув знов їх в layout..

2023-09-05 07:58 UTC, sergio-nezhigay commented on src/sections/Hero/Hero.jsx
> +    <section id="hero" className="hero-bgcolor relative h-auto overflow-hidden">
ід убрав поки

2023-09-05 08:18 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +    <section id="hero" className="hero-bgcolor relative h-auto overflow-hidden">
поправка - ід повинно бути, тільки забирати з data

2023-09-05 09:56 UTC, nadiakhoptiuk approved these changes

2023-09-05 09:56 UTC, merged