Feature/navbar
SoftRyzen-internship/IM-CONSULTING pull request #16
Opened 2023-09-04 20:21 UTC by BogdanGlazkov

2023-09-05 10:39 UTC, nadiakhoptiuk requested changes

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  const mobileStyles = 'flex flex-col w-[168px] gap-[50px] mx-auto xl:hidden';
mobile мається на увазі для меню? може перейменувати, а то не дуже зрозуміло

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +    'hidden mx-auto xl:flex xl:flex-col xl:gap-8 xl:w-[117px] xl:absolute xl:top-1/2 xl:left-0 xl:transform xl:-translate-y-1/2';
на десктопі не по сітці 
https://prnt.sc/Cs_TX6yUBLTn

потрібно fixed а не absolute до контейнера

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +        <NavBar type="dark" />
це не буде у герої, це ж фіксований на сторінці елемент. він взагалі у лейауті тут буде, єдине що від path буде змінювати свій функціонал

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  type: PropTypes.string,
тут мабуть обовязковий + протипізуй, які значення приймає (меню і десктоп)

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/styles/globals.css
> +    @apply relative xl:pl-[236px];
для чого нам це? по-перше, десь щось може поламати на певній секції, по-друге, якщо для фіксації навбару, то він буде фіксований відносно вікна перегляду

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/components/LinkNavBar/LinkNavBar.jsx
> +            : 'xl:text-black xl:opacity-25 xl:hover:opacity-100 xl:focus:opacity-100 '
все таки додай transition згідно з доками

2023-09-05 10:39 UTC, nadiakhoptiuk commented on src/components/LinkNavBar/LinkNavBar.jsx
> +  type: PropTypes.string,
тип - коли має прокидуватись? 
навбар фіксований на сторінці, а не в кожній секції, тому прокинути тип dark чи light не вийде

2023-09-05 12:24 UTC, BogdanGlazkov commented on src/components/LinkNavBar/LinkNavBar.jsx
> +            : 'xl:text-black xl:opacity-25 xl:hover:opacity-100 xl:focus:opacity-100 '
+

2023-09-05 12:25 UTC, BogdanGlazkov commented on src/styles/globals.css
> +    @apply relative xl:pl-[236px];
+

2023-09-05 12:26 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +        <NavBar type="dark" />
+

2023-09-05 12:26 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +    'hidden mx-auto xl:flex xl:flex-col xl:gap-8 xl:w-[117px] xl:absolute xl:top-1/2 xl:left-0 xl:transform xl:-translate-y-1/2';
+

2023-09-05 13:40 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +  const mobileStyles = 'flex flex-col w-[168px] gap-[50px] mx-auto xl:hidden';
+

2023-09-05 13:42 UTC, BogdanGlazkov commented on src/components/NavBar/NavBar.jsx
> +  type: PropTypes.string,
Поки що це прибрав

2023-09-05 13:42 UTC, BogdanGlazkov commented on src/components/LinkNavBar/LinkNavBar.jsx
> +  type: PropTypes.string,
+

2023-09-05 15:09 UTC, nadiakhoptiuk requested changes

2023-09-05 15:09 UTC, nadiakhoptiuk commented on src/layout/NavBar/NavBar.jsx
> +  isDesktop: PropTypes.bool.isRequired,
не бачу сенсу юзати пропс, який завжди true

краще зробити пропс menu, за умовч false, на меню поставиш menu true

2023-09-05 15:09 UTC, nadiakhoptiuk commented on src/sections/Reviews/Reviews.jsx
>          <p>It is Reviews section</p>
це поки все зайве

2023-09-05 15:09 UTC, nadiakhoptiuk commented on src/layout/NavBar/NavBar.jsx
> +      <p className="text-red">Звʼязатися</p>
кнопку уже можна додати, вона є

2023-09-05 15:27 UTC, BogdanGlazkov commented on src/layout/NavBar/NavBar.jsx
> +      <p className="text-red">Звʼязатися</p>
+

2023-09-05 15:27 UTC, BogdanGlazkov commented on src/sections/Reviews/Reviews.jsx
>          <p>It is Reviews section</p>
+

2023-09-05 15:28 UTC, BogdanGlazkov commented on src/layout/NavBar/NavBar.jsx
> +  isDesktop: PropTypes.bool.isRequired,
+

2023-09-06 09:18 UTC, nadiakhoptiuk approved these changes

2023-09-06 09:20 UTC, merged