Feature/form
SoftRyzen-internship/IM-CONSULTING pull request #17
Opened 2023-09-04 20:22 UTC by dianaforost

2023-09-05 08:46 UTC, nadiakhoptiuk requested changes

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +import ErrorIcon from 'public/icons/close.svg';
картинки, іконки, стилі - в кінці

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +import { Loader } from '../Loader';
розділити компоненти і утиліти/дата в імпортах,
відступити між імпортами і компонентом

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +            {...register('name', {})}
фігурні дужки порожні

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +            {...register('email', {})}
фігурні дужки

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +            {...register('message', {})}
фігурні дужки

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +          onClick={onClick}
функція, яка спрацьовує при кліку на кнопку з типом сабміт, це функція сабміту і вона тут вказується на тег form

2023-09-05 08:46 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +      errors.name ||
думаю, тут достатньо перевірити, чи є хоч одна з помилок, на undefined зайве,

статус форми, це коли у тебе на кнопці показується "помилка", тобто це уже після сабміту, якщо щось пішло не так. тоді навіщо викликати сабміт після цього?

2023-09-05 08:49 UTC, nadiakhoptiuk requested changes

2023-09-05 08:49 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +            formStatus === 'success'
це дуже складно читається, краще переписати на кілька тернарників

2023-09-05 08:49 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +          <input
компонент інпута в ідеалі винести, і зробити перевикористовуваним

2023-09-05 09:35 UTC, dianaforost commented on src/components/Form/Form.jsx
> +          <input
Виправлено

2023-09-05 09:36 UTC, dianaforost commented on src/components/Form/Form.jsx
> +            formStatus === 'success'
Виправлено

2023-09-05 09:36 UTC, dianaforost commented on src/components/Form/Form.jsx
> +      errors.name ||
Виправлено

2023-09-05 09:36 UTC, dianaforost commented on src/components/Form/Form.jsx
> +          onClick={onClick}
Виправлено

2023-09-05 09:36 UTC, dianaforost commented on src/components/Form/Form.jsx
> +            {...register('message', {})}
Виправлено

2023-09-05 09:36 UTC, dianaforost commented on src/components/Form/Form.jsx
> +import { Loader } from '../Loader';
Виправлено

2023-09-05 09:36 UTC, dianaforost commented on src/components/Form/Form.jsx
> +import ErrorIcon from 'public/icons/close.svg';
Виправлено

2023-09-06 09:48 UTC, nadiakhoptiuk requested changes

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +      <div className="flex items-center gap-[20px]">
цей тайтл ми не вносимо всередину форми, він буде на секції перед компонентом форми

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +    text-center w-[212px] py-[8px]
цей рядок можна перемістити нижче, до загальних стилів

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/InputField/InputField.jsx
> +    {type === 'textarea' ? (
між умовами рендеру дуже добре робити відступ для полегшення читання

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/utils/yupSchema.js
> +    .required(data.form.emailInvalid),
required треба ставити першим, бо може на пусте поле видавати помилку, що має бути мінімум 6 символів, але помилка обовязковості ніколи не покажеться

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +  useFormPersist('form', {
треба зробити кастомну назву, бо мені одразу підтягнуло інші дані (це тому що один локал хост, але краще додати якесь im_cons чи щось таке)

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/InputField/InputField.jsx
> +      <p
для текстареа кастомізувати
https://prnt.sc/icw3XLnUeYl6

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +        <button
задати висоту кнопці, бо поки вертиться спінер, вона маленька
https://prnt.sc/EXaaHhl-DDmw

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/InputField/InputField.jsx
> +        }  bg-transparent border-[1px] border-solid border-bgColor focus:outline-none p-[8px] md:p-[12px] text-[16px] font-light leading-[20px]  md:text-[20px] md:leading-[24px] xl:text-[24px] xl:lea
focus:outline-none - аутлайн при фокусі не можна знімати, це доступність

2023-09-06 09:48 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +    text-[24px] text-black font-normal line-height-[29px] hover:font-medium focus:font-medium focus:outline-none
так само - аутлайн повернути

2023-09-06 11:09 UTC, dianaforost commented on src/components/Form/Form.jsx
> +      <div className="flex items-center gap-[20px]">
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/Form/Form.jsx
> +    text-center w-[212px] py-[8px]
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/InputField/InputField.jsx
> +    {type === 'textarea' ? (
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/utils/yupSchema.js
> +    .required(data.form.emailInvalid),
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/Form/Form.jsx
> +  useFormPersist('form', {
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/InputField/InputField.jsx
> +      <p
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/Form/Form.jsx
> +        <button
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/InputField/InputField.jsx
> +        }  bg-transparent border-[1px] border-solid border-bgColor focus:outline-none p-[8px] md:p-[12px] text-[16px] font-light leading-[20px]  md:text-[20px] md:leading-[24px] xl:text-[24px] xl:lea
Виправлено.

2023-09-06 11:09 UTC, dianaforost commented on src/components/Form/Form.jsx
> +    text-[24px] text-black font-normal line-height-[29px] hover:font-medium focus:font-medium focus:outline-none
Виправлено.

2023-09-06 15:48 UTC, nadiakhoptiuk approved these changes
прибрати логи у формі, і вставити форму у модалку

2023-09-06 17:54 UTC, merged