Feature/services
SoftRyzen-internship/IM-CONSULTING pull request #19
Opened 2023-09-05 17:12 UTC by dianaforost

2023-09-05 18:27 UTC, BogdanGlazkov requested changes

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/sections/Services/Services.jsx
> +      id="services"
Визначити id за допомогою функції labelToLink, за зразком як у Hero

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCardList/ServicesCardList.jsx
> +  return (
Відступ перед return

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCardList/ServicesCardList.jsx
> +
Відступ зайвий

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +
Зовнішні імпорти разом, потім після відступу внутрішні імпорти

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/styles/globals.css
> +  transform: translateY(-100%);
Спробуй перенести ці стилі у компонент (це можна зробити через group)

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="bg-white flex flex-col justify-between font-normal text-14px leading-1.5 tracking-0.03em text-basic-color h-full w-full absolute top-0 left-0 bg-white xl:gap-[16px]">
bg-white двічі написано, Tailwind підкреслює попередження

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +  text: PropTypes.string.isRequired,
text це масив строк

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="services-card transform translate-y-0 transition-transform duration-500 ease-in-out relative hidden xl:block z-[1]">
z-[1] можна замінити на z-10, щоб код був у одному стилі

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="bg-accent absolute top-[0] w-[100%] h-[100%] opacity-[0.7]"></div>
Тут можна opacity-70, це те ж саме, але простіше

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="bg-accent absolute top-[0] w-[100%] h-[100%] opacity-[0.7]"></div>
w-[100%] h-[100%] краще записати нативними w-full h-full

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="bg-accent absolute top-[0] w-[100%] h-[100%] opacity-[0.7]"></div>
top-[0] - знов зайві дужки, тут просто top-0

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="bg-white flex flex-col justify-between font-normal text-14px leading-1.5 tracking-0.03em text-basic-color h-full w-full absolute top-0 left-0 bg-white xl:gap-[16px]">
font-normal встановлений на сторінці за замовчуванням, тут повторювати не потрібно

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="bg-white flex flex-col justify-between font-normal text-14px leading-1.5 tracking-0.03em text-basic-color h-full w-full absolute top-0 left-0 bg-white xl:gap-[16px]">
text-14px leading-1.5 tracking-0.03em text-basic-color - що це за стилі? Наведи курсор і побачиш, що Tailwind таке не підтримує

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="flex flex-col gap-[24px] pt-[48px] px-[20px] md:pt[40px] md:px-[24px] xl:gap-[16px]">
md:pt[40px] - дефіс забула
Наведи мишкою та перевір будь-ласка кожен клас, чи все приміняється

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +          className="w-[100%] py-[16px] bg-accent hover:bg-darkOrange focus:bg-darkOrange flex justify-center items-center gap-[16px] md:gap-[12px] font-medium text-[24px] leading-[29px] md:text-[20p
md:leadinh-[24px]  очепятка

2023-09-05 18:27 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +          {btnText} <DownArrow />
Розбити на 2 строки

2023-09-05 19:04 UTC, dianaforost commented on src/sections/Services/Services.jsx
> +      id="services"
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCardList/ServicesCardList.jsx
> +  return (
Це мені не дає зробити eslint та prettier. Або можливо не так зрозуміла

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCardList/ServicesCardList.jsx
> +
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/styles/globals.css
> +  transform: translateY(-100%);
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="services-card transform translate-y-0 transition-transform duration-500 ease-in-out relative hidden xl:block z-[1]">
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="bg-accent absolute top-[0] w-[100%] h-[100%] opacity-[0.7]"></div>
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="flex flex-col gap-[24px] pt-[48px] px-[20px] md:pt[40px] md:px-[24px] xl:gap-[16px]">
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +          className="w-[100%] py-[16px] bg-accent hover:bg-darkOrange focus:bg-darkOrange flex justify-center items-center gap-[16px] md:gap-[12px] font-medium text-[24px] leading-[29px] md:text-[20p
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +          {btnText} <DownArrow />
Виправлено

2023-09-05 19:05 UTC, dianaforost commented on src/sections/Services/Services.jsx
> +      id="services"
Виправлено

2023-09-05 19:06 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="bg-white flex flex-col justify-between font-normal text-14px leading-1.5 tracking-0.03em text-basic-color h-full w-full absolute top-0 left-0 bg-white xl:gap-[16px]">
Виправлено

2023-09-05 19:06 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +  text: PropTypes.string.isRequired,
Виправлено

2023-09-06 09:25 UTC, BogdanGlazkov requested changes

2023-09-06 09:25 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +
DownArrow це внутрішній імпорт, перед ним треба відступ

2023-09-06 09:25 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +          {btnText} <DownArrow />
Не виправлено. DownArrow  перенести на нову строку

2023-09-06 09:25 UTC, BogdanGlazkov commented on src/sections/Services/Services.jsx
> +  const id = labelToLink('Головна');
В тебе не головна секція, головна це hero. Подивись назву секції у навігації у data.json

2023-09-06 09:25 UTC, BogdanGlazkov commented on src/components/ServicesCardList/ServicesCardList.jsx
> +  return (
А чому мені дає? Просто нажми Enter перед return

2023-09-06 09:25 UTC, BogdanGlazkov commented on src/components/ServicesCardList/ServicesCardList.jsx
> +import { ServicesCard } from '../ServicesCard/ServicesCard';
import { ServicesCard } from '../ServicesCard';

2023-09-06 09:25 UTC, BogdanGlazkov commented on src/components/ServicesCardList/ServicesCardList.jsx
> +import servicesThirdPhoto from '/public/images/services/servicesThirdPhoto.jpg';
Картинки краще перейменувати, не використовуючи у назві великі літери. Наприклад services1, services2 і т.д.

2023-09-06 09:43 UTC, BogdanGlazkov requested changes

2023-09-06 09:43 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        md:gap-[12px] font-medium text-[24px] leading-[29px] md:text-[20px] md:leading-[24px] xl:text-[24px] xl:leading-[29px] xl:py-[20px]"
Перевірити letter-spacing

2023-09-06 09:43 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        md:gap-[12px] font-medium text-[24px] leading-[29px] md:text-[20px] md:leading-[24px] xl:text-[24px] xl:leading-[29px] xl:py-[20px]"
На планшеті py-[12px]

2023-09-06 09:43 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +        <p className="absolute bottom-[48px] left-[24px] xl:text-[42px] xl:leading-[51px]">
Додати letter-spacing

2023-09-06 09:43 UTC, BogdanGlazkov commented on src/components/ServicesCardList/ServicesCardList.jsx
> +      <ul className="flex flex-col gap-[16px] justify-center items-center md:flex-row md:gap-[12px]">
xl:gap-[20px]

2023-09-06 10:11 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +
Виправлено.

2023-09-06 10:12 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +          {btnText} <DownArrow />
Виправлено.

2023-09-06 10:12 UTC, dianaforost commented on src/sections/Services/Services.jsx
> +  const id = labelToLink('Головна');
Вибач, не помітила. Виправлено.

2023-09-06 10:12 UTC, dianaforost commented on src/components/ServicesCardList/ServicesCardList.jsx
> +import { ServicesCard } from '../ServicesCard/ServicesCard';
Виправлено.

2023-09-06 10:13 UTC, dianaforost commented on src/components/ServicesCardList/ServicesCardList.jsx
> +import servicesThirdPhoto from '/public/images/services/servicesThirdPhoto.jpg';
Виправлено.

2023-09-06 10:13 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +        md:gap-[12px] font-medium text-[24px] leading-[29px] md:text-[20px] md:leading-[24px] xl:text-[24px] xl:leading-[29px] xl:py-[20px]"
Виправлено.

2023-09-06 10:13 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +        <p className="absolute bottom-[48px] left-[24px] xl:text-[42px] xl:leading-[51px]">
Виправлено.

2023-09-06 10:13 UTC, dianaforost commented on src/components/ServicesCardList/ServicesCardList.jsx
> +      <ul className="flex flex-col gap-[16px] justify-center items-center md:flex-row md:gap-[12px]">
Виправлено.

2023-09-06 10:15 UTC, dianaforost commented on src/components/ServicesCardList/ServicesCardList.jsx
> +  return (
Вибач, я не так зрозуміла. Виправлено.

2023-09-06 10:37 UTC, BogdanGlazkov requested changes

2023-09-06 10:37 UTC, BogdanGlazkov commented on src/components/ServicesCard/ServicesCard.jsx
> +          className="w-full py-[16px] tracking-[0.1em] bg-accent hover:bg-darkOrange focus:bg-darkOrange flex justify-center items-center gap-[16px]
До hover і focus додати transition та duration-300

2023-09-06 10:55 UTC, dianaforost commented on src/components/ServicesCard/ServicesCard.jsx
> +          className="w-full py-[16px] tracking-[0.1em] bg-accent hover:bg-darkOrange focus:bg-darkOrange flex justify-center items-center gap-[16px]
Виправлено.

2023-09-06 11:12 UTC, nadiakhoptiuk commented on src/data/data.json
давай винесемо у data/home/services.json весь цей обєкт

2023-09-06 11:12 UTC, nadiakhoptiuk commented on public/images/services/services1.jpg
ці картинки трохи не так виглядають, там є ще один оверлей. я попрошу Віталія обєднати, або можеш сама (у групу)

2023-09-06 11:12 UTC, nadiakhoptiuk commented on src/components/ServicesCard/ServicesCard.jsx
> +      <div className="services-card transform translate-y-0 transition-transform duration-500 ease-in-out relative hidden xl:block z-[1]">
може бути і 1, без проблем, це просто кастомні стилі

2023-09-06 11:16 UTC, BogdanGlazkov approved these changes

2023-09-06 11:21 UTC, dianaforost commented on public/images/services/services1.jpg
Тобто фото + оверлей + цей жовтий оверлей?

2023-09-06 11:45 UTC, nadiakhoptiuk requested changes

2023-09-06 11:45 UTC, nadiakhoptiuk commented on public/images/services/services1.jpg
так

2023-09-06 12:00 UTC, dianaforost commented on public/images/services/services1.jpg
Виправлено.

2023-09-06 12:00 UTC, dianaforost commented on src/data/data.json
Виправлено.

2023-09-06 14:57 UTC, nadiakhoptiuk approved these changes

2023-09-06 14:57 UTC, merged