Feature/config
SoftRyzen-internship/IM-CONSULTING pull request #2
Opened 2023-08-31 20:53 UTC by BogdanGlazkov

2023-09-01 09:38 UTC, nadiakhoptiuk requested changes

2023-09-01 09:38 UTC, nadiakhoptiuk commented on src/app/layout.jsx
> -const inter = Inter({ subsets: ['latin'] });
імпортуй шрифт, будь ласка, як раніше 'next/font/google'

2023-09-01 09:38 UTC, nadiakhoptiuk commented on tailwind.config.js
> +      xl: '1440px',
у нас буде 1280 і відповідно по 32 падінги

2023-09-01 09:38 UTC, nadiakhoptiuk commented on tailwind.config.js
>          inter: ['Inter', 'sans-serif'],
тут інтер, якщо зайвий, прибрати

2023-09-01 09:38 UTC, nadiakhoptiuk commented on tailwind.config.js
> +        8: ['8px'],
краще не додавати ці цифри, всі можуть на 4 поділити, але додати кастомні шрифти
https://prnt.sc/pav6AOjeLhRG
https://prnt.sc/gH-s6E344C87
https://prnt.sc/h4WLQqxhndUi
і тд

2023-09-01 12:38 UTC, BogdanGlazkov commented on src/app/layout.jsx
> -const inter = Inter({ subsets: ['latin'] });
Це кастомний, його немає в Гуглі

2023-09-01 12:39 UTC, BogdanGlazkov commented on tailwind.config.js
> +      xl: '1440px',
+

2023-09-01 12:42 UTC, BogdanGlazkov commented on tailwind.config.js
>          inter: ['Inter', 'sans-serif'],
+

2023-09-01 12:44 UTC, BogdanGlazkov commented on src/app/layout.jsx
> -const inter = Inter({ subsets: ['latin'] });
Завантажив у окремій папці

2023-09-01 15:23 UTC, BogdanGlazkov commented on tailwind.config.js
> +        8: ['8px'],
Ок

2023-09-01 15:43 UTC, nadiakhoptiuk requested changes

2023-09-01 15:43 UTC, nadiakhoptiuk commented on data/data.json
> +    "connect": "Звʼязатися"
треба кнопку окремо Звʼязатися, там на ній буде інший функціонал, + додати ід якорних посилань

2023-09-01 15:43 UTC, nadiakhoptiuk commented on data/data.json
> +    "title1": "IM",
цей тайтл буде скоріш за все фоном..

2023-09-01 15:46 UTC, BogdanGlazkov commented on data/data.json
> +    "title1": "IM",
+

2023-09-01 15:57 UTC, BogdanGlazkov commented on data/data.json
> +    "connect": "Звʼязатися"
+

2023-09-02 07:37 UTC, nadiakhoptiuk approved these changes

2023-09-02 07:37 UTC, merged