Feature/section process
SoftRyzen-internship/IM-CONSULTING pull request #20
Opened 2023-09-06 07:16 UTC by Nataly-Moskalenko

2023-09-06 08:07 UTC, BogdanGlazkov requested changes

2023-09-06 08:07 UTC, BogdanGlazkov commented on src/components/ProcessCard/ProcessCard.jsx
> +        />
Усі теги Image повинні мати атрибут quality={100}

2023-09-06 08:07 UTC, BogdanGlazkov commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
Перед ul можна зробити відступ для читабельності

2023-09-06 08:07 UTC, BogdanGlazkov commented on src/data/data.json
> +        "src": "/images/process/ProcessPhoto1@2x.jpg",
Назви фото у нижньому регисті кебаб-кейсом. Можна просто process1, process2 і т.д. 
@2x з назви можна прибрати, бо інших версій цього фото не планується

2023-09-06 08:07 UTC, BogdanGlazkov commented on src/sections/Process/Process.jsx
> +  return (
Відступ перед return

2023-09-06 08:29 UTC, BogdanGlazkov requested changes

2023-09-06 08:29 UTC, BogdanGlazkov commented on src/components/ProcessCard/ProcessCard.jsx
> +            <span className="mx-[12px] font-bold">{subtitle}</span>
На планшеті марджин збільшити

2023-09-06 08:29 UTC, BogdanGlazkov commented on src/components/ProcessContent/ProcessContent.jsx
> +        <span className="mx-[12px] ">{data.process.title}</span>
На планшеті марджин збільшити

2023-09-06 08:49 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +        />
додала

2023-09-06 09:17 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +            <span className="mx-[12px] font-bold">{subtitle}</span>
виправила

2023-09-06 09:18 UTC, Nataly-Moskalenko commented on src/components/ProcessContent/ProcessContent.jsx
> +        <span className="mx-[12px] ">{data.process.title}</span>
виправила

2023-09-06 09:18 UTC, Nataly-Moskalenko commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
+

2023-09-06 09:19 UTC, Nataly-Moskalenko commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
ок

2023-09-06 09:21 UTC, Nataly-Moskalenko commented on src/data/data.json
> +        "src": "/images/process/ProcessPhoto1@2x.jpg",
ок

2023-09-06 09:23 UTC, Nataly-Moskalenko commented on src/sections/Process/Process.jsx
> +  return (
ок

2023-09-06 14:22 UTC, nadiakhoptiuk requested changes

2023-09-06 14:22 UTC, nadiakhoptiuk commented on src/components/ProcessContent/ProcessContent.jsx
> +      <h2 className="sr-only">Process Section</h2>
цей заголовок в ідеалі перенести у секцію

2023-09-06 14:22 UTC, nadiakhoptiuk commented on src/components/ProcessCard/ProcessCard.jsx
> +            number === '02' || number === '04' ? 'flex-row-reverse' : 'flex-row'
краще перевірити на непарність

2023-09-06 14:22 UTC, nadiakhoptiuk commented on src/components/ProcessCard/ProcessCard.jsx
> +          <div className="w-[59px] h-[59px] md:w-[94px] md:h-[88px] xl:w-[108px] xl:h-[100px] text-orange text-[48px] font-light tracking-[4.8px] opacity-10 md:text-[72px] md:tracking-[7.2px] xl:text
це більше на спан схоже, не дів

2023-09-06 14:22 UTC, nadiakhoptiuk commented on src/components/ProcessCard/ProcessCard.jsx
> +            <span className="text-orange">[ </span>
для цих текстів є компонент тайтл, Настя додала, зараз скоро його злиємо

2023-09-06 14:31 UTC, Nataly-Moskalenko commented on src/components/ProcessContent/ProcessContent.jsx
> +      <h2 className="sr-only">Process Section</h2>
перенесла

2023-09-06 14:36 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +            number === '02' || number === '04' ? 'flex-row-reverse' : 'flex-row'
ок

2023-09-06 14:37 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +          <div className="w-[59px] h-[59px] md:w-[94px] md:h-[88px] xl:w-[108px] xl:h-[100px] text-orange text-[48px] font-light tracking-[4.8px] opacity-10 md:text-[72px] md:tracking-[7.2px] xl:text
виправила

2023-09-06 14:38 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +            <span className="text-orange">[ </span>
ок

2023-09-07 07:52 UTC, nadiakhoptiuk requested changes

2023-09-07 07:52 UTC, nadiakhoptiuk commented on src/components/ProcessCard/ProcessCard.jsx
> +    <div className="flex flex-col md:flex-row-reverse md:even:flex-row gap-[16px] md:gap-[24px] xl:gap-[32px] max-w-[480px] md:w-[696px] md:max-w-[696px] xl:w-[1012px] xl:max-w-[1012px] text-right ev
тільки li може бути дочірнім елементом списку ul

2023-09-07 07:52 UTC, nadiakhoptiuk commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
тут gap таблет 56, десктоп 146

2023-09-07 07:52 UTC, nadiakhoptiuk commented on src/components/ProcessCard/ProcessCard.jsx
> +      <div className=" mx-auto w-[280px] h-[200px] md:w-[342px] md:h-[256px] xl:w-[500px] xl:h-[376px] md:mt-[20px] opacity-85">
тут mt не задавати, і позбутись діва, він зайвий і зі старими стилями, а ті що потрібні - перенести на картинку.

2023-09-07 07:52 UTC, nadiakhoptiuk commented on src/components/ProcessCard/ProcessCard.jsx
> +          className="w-[280px] h-[200px] md:w-[342px] md:h-[256px] xl:w-[500px] xl:h-[376px]"
на мобільному можна зробити, щоб зображення тягнулося
https://prnt.sc/nU_fn0quEKyp

перевірити, щоб максимальна ширина не впливала на таблет і десктоп (перезадати, або задати тут max-md:max-w-[440px])

2023-09-07 07:59 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +    <div className="flex flex-col md:flex-row-reverse md:even:flex-row gap-[16px] md:gap-[24px] xl:gap-[32px] max-w-[480px] md:w-[696px] md:max-w-[696px] xl:w-[1012px] xl:max-w-[1012px] text-right ev
виправила

2023-09-07 08:02 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +      <div className=" mx-auto w-[280px] h-[200px] md:w-[342px] md:h-[256px] xl:w-[500px] xl:h-[376px] md:mt-[20px] opacity-85">
div видалила

2023-09-07 08:08 UTC, Nataly-Moskalenko commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
змінила

2023-09-07 08:18 UTC, Nataly-Moskalenko commented on src/components/ProcessCard/ProcessCard.jsx
> +          className="w-[280px] h-[200px] md:w-[342px] md:h-[256px] xl:w-[500px] xl:h-[376px]"
ок

2023-09-07 11:21 UTC, nadiakhoptiuk commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
мобільний 36

2023-09-07 11:25 UTC, nadiakhoptiuk commented on src/components/ProcessContent/ProcessContent.jsx
> +      <ul className="flex flex-col gap-[36px] xl:gap-[124px] items-center">
файл data.json видалити

2023-09-07 11:37 UTC, nadiakhoptiuk approved these changes

2023-09-07 11:38 UTC, nadiakhoptiuk approved these changes

2023-09-07 11:40 UTC, merged