Feature/mobile menu
SoftRyzen-internship/IM-CONSULTING pull request #22
Opened 2023-09-06 19:58 UTC by BogdanGlazkov

2023-09-07 11:06 UTC, nadiakhoptiuk requested changes

2023-09-07 11:06 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +        {isMobile && isMenuOpen && (
тут прибери умову isMenuOpen, бо в тебе буде рендеритися меню щоразу, тобто додаватися в дерево

2023-09-07 11:06 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +          <MobileMenu handleMenuToggle={handleMenuToggle} />
а в саме меню прокидуй isMenuOpen і залежно від неї зроби якусь анімацію, плавну появу

2023-09-07 11:06 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex items-center w-[34%]  md:w-[148px] h-[100vh]">
чорна смужка на мобільному завжди 88px, далі - згідно з макетом. в тебе зараз вона завжди рухається, а текст фіксований. треба подумати, як краще зверстати

2023-09-07 18:18 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +        {isMobile && isMenuOpen && (
+

2023-09-07 18:35 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +          <MobileMenu handleMenuToggle={handleMenuToggle} />
+

2023-09-07 18:48 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex items-center w-[34%]  md:w-[148px] h-[100vh]">
+

2023-09-08 13:57 UTC, nadiakhoptiuk requested changes
і перевірити транзішин для меню

2023-09-08 13:57 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex items-center w-[34%]  md:w-[148px] h-[100vh]">
тут 34% змушують їздити контент, постав фіксовану ширину 68px (для таблета 112) i flex-shrink-0

2023-09-08 13:57 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex items-center md:justify-center w-full md:w-[620px] pl-6">
для таблета прибери ширини всі і постав pl 226px

2023-09-08 14:14 UTC, BogdanGlazkov commented on src/components/MobileMenu/MobileMenu.jsx
> +        <div className="flex items-center md:justify-center w-full md:w-[620px] pl-6">
Transition додав

2023-09-08 15:39 UTC, nadiakhoptiuk reviewed
меню ок, але оскільки тут є код хедера, на який я в ін ПР писала ревю, не зливаю. можеш цю гілку злити в гілку менюшки і фіксити там далі меню

2023-09-08 19:21 UTC, BogdanGlazkov commented
Ок, переніс все у гілку хедер

2023-09-11 08:42 UTC, BogdanGlazkov commented
Цю гілку можна видаляти

2023-09-11 08:43 UTC, BogdanGlazkov commented
Цю гілку можна видаляти

2023-09-11 08:43 UTC, closed without merging