Feature/section contacts
SoftRyzen-internship/IM-CONSULTING pull request #23
Opened 2023-09-07 06:44 UTC by Nataly-Moskalenko

2023-09-07 08:11 UTC, BogdanGlazkov requested changes

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/sections/Contacts/Contacts.jsx
> +  return (
Відступ перед return

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/sections/Contacts/Contacts.jsx
> +      <Container className="">
Пустий className писати не треба

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsContent/ContactsContent.jsx
> +          className="contacts-title mx-auto mb-[32px] md:mb[36px] xl:mb-[48px] w-[280px] md:w-[342px] xl:w-[500px]"
md:mb[36px] дефіс пропустили

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsCard/ContactsCard.jsx
> +          className="contacts-title mx-auto mb-[32px] md:mb[36px] xl:mb-[48px]"
md:mb[36px] дефіс пропустили

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsCard/ContactsCard.jsx
> +        <ul>
Перед ul відступ для читабельності

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsCard/ContactsCard.jsx
> +          <li className="flex gap-[12px] mb-[32px] md:mb[36px] xl:mb-[48px]">
md:mb[36px] бракує дефіса

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsCard/ContactsCard.jsx
> +          <li className="flex gap-[12px] mb-[32px] md:mb[36px] xl:mb-[48px]">
md:mb[36px] бракує дефіса

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsCard/ContactsCard.jsx
> +          className="contacts-title mx-auto mb-[32px] md:mb[36px] xl:mb-[48px]"
md:mb[36px] бракує дефіса

2023-09-07 08:11 UTC, BogdanGlazkov commented on src/components/ContactsCard/ContactsCard.jsx
> +                    className="font-light first:mb-[4px] md:first:mb-[8px} hover:text-accent focus:text-accent transition duration-300"
md:first:mb-[8px} - невірна дужка

2023-09-07 09:21 UTC, Nataly-Moskalenko commented on src/sections/Contacts/Contacts.jsx
> +  return (
ок

2023-09-07 09:21 UTC, Nataly-Moskalenko commented on src/sections/Contacts/Contacts.jsx
> +      <Container className="">
ок

2023-09-07 09:22 UTC, Nataly-Moskalenko commented on src/components/ContactsContent/ContactsContent.jsx
> +          className="contacts-title mx-auto mb-[32px] md:mb[36px] xl:mb-[48px] w-[280px] md:w-[342px] xl:w-[500px]"
виправила

2023-09-07 09:23 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +          className="contacts-title mx-auto mb-[32px] md:mb[36px] xl:mb-[48px]"
виправила

2023-09-07 09:23 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +        <ul>
ок

2023-09-07 09:23 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +          <li className="flex gap-[12px] mb-[32px] md:mb[36px] xl:mb-[48px]">
ок

2023-09-07 09:24 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +                    className="font-light first:mb-[4px] md:first:mb-[8px} hover:text-accent focus:text-accent transition duration-300"
виправила

2023-09-07 09:24 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +          <li className="flex gap-[12px] mb-[32px] md:mb[36px] xl:mb-[48px]">
виправила

2023-09-07 09:25 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +          className="contacts-title mx-auto mb-[32px] md:mb[36px] xl:mb-[48px]"
виправила

2023-09-07 12:00 UTC, nadiakhoptiuk requested changes

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/app/page.jsx
> +import { Contacts } from '@/sections/Contacts';
імпорти повинні бути в порядку появи на сторінці в ідеалі, можна тут виправити, хоча це всіх компоненти

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/components/ConnectButton/ConnectButton.jsx
> +          </Title>
тут внизу для пропа color краще обмежити, які саме назви кольорів він приймає

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/components/ContactsCard/ContactsCard.jsx
> +import data from '@/data/data.json';
винесено у contacts.json, data видалити

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/components/ContactsContent/ContactsContent.jsx
> +import data from '@/data/data.json';
так само contacts.json

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/data/data.json
видалити цей файл

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/sections/Contacts/Contacts.jsx
> +      <Container>
в ідеалі тут поставити прихований заголовок h2 контакти, а інші зробити h3, бо їх 3 шт

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/components/ContactsCard/ContactsCard.jsx
> +              target="_blank"
для пошти target="_blank" треба прибрати, бо моргає сторінка

2023-09-07 12:00 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +export const Form = () => {
треба підкорегувати стилі, щоб на мобільному у секції контакти форма була на 440
в ідеалі її робити w-full, а обмежувати ширину дівів, у які вона поміщається (наприклад, модалку падінгами, а в секції дів шириною
https://prnt.sc/8BdMpC7HqS4E

2023-09-07 14:19 UTC, Nataly-Moskalenko commented on src/app/page.jsx
> +import { Contacts } from '@/sections/Contacts';
виправила

2023-09-07 14:26 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +          </Title>
ок

2023-09-07 14:27 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +import data from '@/data/data.json';
ок

2023-09-07 14:28 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +              target="_blank"
ок

2023-09-07 14:29 UTC, Nataly-Moskalenko commented on src/components/ContactsContent/ContactsContent.jsx
> +import data from '@/data/data.json';
ок

2023-09-07 14:33 UTC, Nataly-Moskalenko commented on src/components/Form/Form.jsx
> +export const Form = () => {
ок

2023-09-07 14:59 UTC, Nataly-Moskalenko commented on src/data/data.json
видалила

2023-09-07 15:03 UTC, Nataly-Moskalenko commented on src/sections/Contacts/Contacts.jsx
> +      <Container>
ок

2023-09-08 08:21 UTC, nadiakhoptiuk requested changes

2023-09-08 08:21 UTC, nadiakhoptiuk commented on src/sections/Contacts/Contacts.jsx
> +      <Container>
Назва повинна бути мовою сайту, тобто українською - "Звязатися з нами"

2023-09-08 08:21 UTC, nadiakhoptiuk commented on src/data/home/contacts.json
> +  "socials": "Соціальні мережі"
в ідеалі можна сюди внести уже дані з файла соцмереж

`"socials": {
title: "Соціальні мережі",
links: [
.....
]
}`

2023-09-08 08:21 UTC, nadiakhoptiuk commented on src/components/ContactsCard/ContactsCard.jsx
> +              rel="noreferrer noopener nofollow"
rel також не потрібен тут

2023-09-08 08:31 UTC, nadiakhoptiuk requested changes

2023-09-08 08:31 UTC, nadiakhoptiuk commented on src/components/ContactsCard/ContactsCard.jsx
> +      <div className="mb-[64px] md:mb-[56px]">
цього діва можна позбутися, задавши відступи на елементи

2023-09-08 08:31 UTC, nadiakhoptiuk commented on src/components/ContactsCard/ContactsCard.jsx
> +    <div className="w-[280px] md:w-[320px] xl:w-[480px]">
тут на таблеті ширина 311

2023-09-08 08:31 UTC, nadiakhoptiuk commented on src/components/ContactsContent/ContactsContent.jsx
> +    <div className="flex flex-col md:flex-row gap-[64px] md:gap-[32px]">
на таблеті gap 43px
і треба піти в конфіг тейлвінда, виправити падінги для таблета, бо вони по 36 px = 2.25rem

2023-09-08 08:47 UTC, Nataly-Moskalenko commented on src/sections/Contacts/Contacts.jsx
> +      <Container>
виправила

2023-09-08 08:56 UTC, Nataly-Moskalenko commented on src/components/ContactsContent/ContactsContent.jsx
> +    <div className="flex flex-col md:flex-row gap-[64px] md:gap-[32px]">
виправила

2023-09-08 09:08 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +              rel="noreferrer noopener nofollow"
ок

2023-09-08 09:09 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +      <div className="mb-[64px] md:mb-[56px]">
ок

2023-09-08 09:43 UTC, Nataly-Moskalenko commented on src/data/home/contacts.json
> +  "socials": "Соціальні мережі"
ок

2023-09-08 09:49 UTC, Nataly-Moskalenko commented on src/components/ContactsCard/ContactsCard.jsx
> +    <div className="w-[280px] md:w-[320px] xl:w-[480px]">
ок

2023-09-08 11:35 UTC, nadiakhoptiuk approved these changes

2023-09-08 11:38 UTC, merged