Feature/reviews
SoftRyzen-internship/IM-CONSULTING pull request #26
Opened 2023-09-07 11:36 UTC by sergio-nezhigay

add reviews and footer sections

2023-09-07 12:38 UTC, BogdanGlazkov requested changes

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/layout/Footer/Footer.jsx
> +            className="hover:text-white transition duration-300"
Додати фокус

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/layout/Footer/Footer.jsx
> +          {title.toUpperCase()}
Замість toUpperCase() краще додати клас uppercase

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/layout/Footer/Footer.jsx
> +};
Додати проптайпси

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/sections/Reviews/Reviews.jsx
> +'use client';
Відступ

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/sections/Reviews/Reviews.jsx
> +import reviews from '@/data/home/reviews.json';
Впорядкувати імпорти (зовнішні разом, після відступу внутрішні)

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/sections/Reviews/Reviews.jsx
> +      <Container className="">
Пустий className додавати не треба

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/components/ReviewCard/ReviewCard.jsx
> +
Можливо треба зафіксувати висоту карток, бо вони скачуть вгору-вниз при прокрутці

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/components/ReviewCard/ReviewCard.jsx
> +        <p className="text-[60px] md:text-[66px] xl:text-[116px] leading-[73px] md:leading-[81px] xl:leading-[142px] opacity-10">
Перевірити letter-spacing

2023-09-07 12:38 UTC, BogdanGlazkov commented on src/components/ReviewCard/ReviewCard.jsx
> +      </p>
На десктопі невірні відступи https://prnt.sc/5JqZba_njzGo

2023-09-07 12:51 UTC, BogdanGlazkov requested changes

2023-09-07 12:51 UTC, BogdanGlazkov commented on src/layout/Footer/Footer.jsx
> +        <p>
font-weight 500

2023-09-07 12:51 UTC, BogdanGlazkov commented on src/layout/Footer/Footer.jsx
> +          {title.toUpperCase()}
На десктопі IM та Consulting мають бути ближче

2023-09-07 12:51 UTC, BogdanGlazkov commented on src/layout/Footer/Footer.jsx
> +            {reserved} {subtitle}
Перевірити letter-spacing

2023-09-07 14:29 UTC, sergio-nezhigay commented on src/layout/Footer/Footer.jsx
> +};
пусті додати, якщо нема пропсів. Чи маєш на увазі що треба рефакторінг компонента?

2023-09-07 14:31 UTC, sergio-nezhigay commented on src/layout/Footer/Footer.jsx
> +        <p>
CONSULTING font-weight 400 бачу на всіх екранах. перевір, будь ласка

2023-09-07 14:36 UTC, sergio-nezhigay commented on src/layout/Footer/Footer.jsx
> +            {reserved} {subtitle}
All rights reserved 2023 © IMConsulting бачу -4%. Минулий раз ти писав "-0.04em це в межах похибки, менше пікселя". Я й перестав робити. Я не так зрозумів ?

2023-09-07 14:38 UTC, nadiakhoptiuk requested changes

2023-09-07 14:38 UTC, nadiakhoptiuk commented on src/components/ReviewCard/ReviewCard.jsx
> +  rating: PropTypes.number.isRequired,
https://prnt.sc/YvNl2Fm7u3cq

2023-09-07 14:38 UTC, nadiakhoptiuk commented on src/sections/Reviews/Reviews.jsx
> +        <Swiper {...swiperParams}>
свайпер з усім, що йому належить (імпорти і тд) потрібно винести у окремий компонент.

2023-09-07 14:38 UTC, nadiakhoptiuk commented on src/sections/Reviews/Reviews.jsx
> +    spaceBetween: 24,
чомусь по факту 32 примінилось і на таблет, а повинно 24

2023-09-07 14:38 UTC, nadiakhoptiuk commented on src/sections/Reviews/swiper-scrollbar.css
цей файл винести у папку стилів

2023-09-07 14:38 UTC, nadiakhoptiuk commented on src/styles/globals.css
> +  .title-brackets {
у нас є чудовий компонент від Анастасії - Title

2023-09-08 07:17 UTC, sergio-nezhigay commented on src/sections/Reviews/Reviews.jsx
> +import reviews from '@/data/home/reviews.json';
виправив

2023-09-08 07:19 UTC, sergio-nezhigay commented on src/components/ReviewCard/ReviewCard.jsx
> +
поставив фіксоване по максимальній картці, обмежив по кількості строк

2023-09-08 07:20 UTC, sergio-nezhigay commented on src/components/ReviewCard/ReviewCard.jsx
> +        <p className="text-[60px] md:text-[66px] xl:text-[116px] leading-[73px] md:leading-[81px] xl:leading-[142px] opacity-10">
помилку на tablet, desktop виправив

2023-09-08 07:20 UTC, sergio-nezhigay commented on src/components/ReviewCard/ReviewCard.jsx
> +      </p>
виправив

2023-09-08 16:19 UTC, nadiakhoptiuk approved these changes

2023-09-08 16:19 UTC, merged