Feature/header
SoftRyzen-internship/IM-CONSULTING pull request #29
Opened 2023-09-07 15:01 UTC by BogdanGlazkov

2023-09-07 15:55 UTC, nadiakhoptiuk reviewed
хедер виглядає ок, тільки транзішин додати

2023-09-08 12:34 UTC, BogdanGlazkov commented
Додав анімацію

2023-09-08 15:17 UTC, nadiakhoptiuk requested changes

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  useEffect(() => {
для меню не потрібно ESC слухати, на таких пристроях немає клавіш

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +      setTimeout(() => setShowHeader(false), 300);
як на мене 200 оптимально

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +    document.addEventListener('scroll', listenCallback);
тут потрібна перевірка, чи десктоп, на десктопі не слухаємо

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +    if (scrollHeight > 1 && isScrollUp) {
тут також потрібна перевірка, чи десктоп, на десктопі return

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +          <ButtonMenuToggle className="w-[18px] fill-black hover:fill-white focus:fill-white transition duration-300" />
це повинна бути кнопка, а не свг!

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  const [scrollHeight, setScrollHeight] = useState(null);
scrollHeight і  isScrollUp я б позбулася

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  useLayoutEffect(() => {
цей юзеефект я б перенесла..

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  const listenCallback = useCallback(() => {
цей я б переписала.
спершу перевірка чи це десктоп - return

`  const listenCallback = useCallback(() => {
    // setScrollHeight(window?.scrollY || document.documentElement.scrollTop);
    const scrollHeight = window?.scrollY || document.documentElement.scrollTop;

    if (scrollHeight > 1 && scrollHeight < lastScrollTop) {
      setTimeout(() => setShowHeader(true), 200);
    } else if (scrollHeight > 1 && scrollHeight > lastScrollTop) {
      setTimeout(() => setShowHeader(false), 200);
    }
    setLastScrollTop(scrollHeight <= 0 ? 0 : scrollHeight);
  }, [lastScrollTop]);`

2023-09-08 15:17 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +      className={`${
тут також перевірка потрібна


`className={`${
        showHeader ? ' max-xl:translate-y-0 ' : ' max-xl:translate-y-[-100%] '
      } header-gradient transition-transform fixed xl:absolute top-0 left-0 right-0 py-[14px] md:py-[36px] z-50 duration-300`}`}`

2023-09-08 15:24 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +  useEffect(() => {
+

2023-09-08 18:15 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +      setTimeout(() => setShowHeader(false), 300);
Змінив на анімацію

2023-09-08 18:20 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +    document.addEventListener('scroll', listenCallback);
+

2023-09-08 18:24 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +    if (scrollHeight > 1 && isScrollUp) {
+

2023-09-08 18:25 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +          <ButtonMenuToggle className="w-[18px] fill-black hover:fill-white focus:fill-white transition duration-300" />
Я забрав звідси моб меню у окрему гілку

2023-09-08 18:31 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +  const [scrollHeight, setScrollHeight] = useState(null);
Тут я визначаю, чи користувач скролить вгору, чи вниз, і відповідно до цього показую хедер чи ні

2023-09-08 18:32 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +  useLayoutEffect(() => {
Він визначає, чи показувати хедер при скролі (показуємо тільки якщо скрол догори)

2023-09-08 18:48 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +  const listenCallback = useCallback(() => {
Спробував, але цей код невірно працює  (хедер відображається не так як треба)

2023-09-08 18:51 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +      className={`${
Переробив

2023-09-08 18:51 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +          <ButtonMenuToggle className="w-[18px] fill-black hover:fill-white focus:fill-white transition duration-300" />
+

2023-09-08 19:20 UTC, BogdanGlazkov commented
Виправив та злив з моб меню

2023-09-11 07:04 UTC, nadiakhoptiuk requested changes

2023-09-11 07:04 UTC, nadiakhoptiuk commented on src/styles/globals.css
> +        #171717 calc(50% - 9px),
підкорегувати
https://prnt.sc/KqK72rUIUHkk

2023-09-11 07:04 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +    setLastScrollTop(scrollHeight <= 0 ? 0 : scrollHeight);
scrollHeight буває < 0?

2023-09-11 07:04 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  const listenCallback = useCallback(() => {
позбутися стейту [isScrollUp, setIsScrollUp], щоб було менше ререндерів
змінити умову scrollHeight <= 0 (не буває)

2023-09-11 07:04 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +      ? document.body.classList.add('overflow-hidden')
скоріш за все, на деяких айфонах ця властивість не працює, будемо дивитись

2023-09-11 07:48 UTC, BogdanGlazkov commented on src/styles/globals.css
> +        #171717 calc(50% - 9px),
Що саме підкорегувати?

2023-09-11 07:51 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +    setLastScrollTop(scrollHeight <= 0 ? 0 : scrollHeight);
Теоретично може бути глюк, що він стане мінусовим. Цей код зі StackOverflow

2023-09-11 08:11 UTC, BogdanGlazkov commented on src/styles/globals.css
> +        #171717 calc(50% - 9px),
+

2023-09-11 08:40 UTC, BogdanGlazkov commented
Все виправив

2023-09-11 11:12 UTC, nadiakhoptiuk approved these changes

2023-09-11 11:12 UTC, merged