Feature/contact button and modal
SoftRyzen-internship/IM-CONSULTING pull request #3
Opened 2023-09-02 14:00 UTC by Nataly-Moskalenko

2023-09-03 10:44 UTC, BogdanGlazkov requested changes

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +import ConnectModal from '../ConnectModal/ConnectModal';
import { ConnectModal } from '../ConnectModal';

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +import { useState } from 'react';
Зовнішні експорти разом, без відступу, react завжди йде перший

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +import Icon from 'public/icons/connect.svg';
У всіх файлах svg треба прибрати width та height, тоді іконки будуть підлаштовуватись під задані розміри

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +        aria-label="Кнопка Зв'язатися"
aria-label тут не потрібен, у кнопки є текст

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +        className={color === "accent" ? "flex items-center gap-2 m-0 p-0 text-accent" : "flex items-center gap-2 m-0 p-0 text-black"}
Тут у тернарнику повторюються стилі, їх треба винести за нього, залишивши тільки кольори. Наприклад 
        className={`flex items-center gap-2 m-0 p-0 ${
          color === 'accent' ? ' text-accent' : ' text-black'
        }  `}

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +        <p className="text-font16 font-formular font-bold leading-[16px]">
font-formular писати не треба, він за замовчуванням встановлений у всьому документі

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +        <p className="text-font16 font-formular font-bold leading-[16px]">
leading для однієї строки писати не треба, краще використати відступи

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +
Зовнішні імпорти разом, при цьому PropTypes в кінці, бо розташований нижче всіх у коді

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +import Icon from 'public/icons/close2.svg';
Чому close2.svg? Може назвати closeModal.svg, щоб було зрозуміліше

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +                aria-label="Кнопка Закрити модальне вікно"
Просто "Закрити". Те, що це кнопка, скрінрідер і так повідомить

2023-09-03 10:44 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +  children: PropTypes.node,
isRequired,

2023-09-03 19:42 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +import ConnectModal from '../ConnectModal/ConnectModal';
виправила

2023-09-03 19:43 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +import { useState } from 'react';
ок

2023-09-03 19:43 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +import Icon from 'public/icons/connect.svg';
ок, прибрала, дякую

2023-09-03 19:44 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +        aria-label="Кнопка Зв'язатися"
виправила

2023-09-03 19:44 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +        className={color === "accent" ? "flex items-center gap-2 m-0 p-0 text-accent" : "flex items-center gap-2 m-0 p-0 text-black"}
виправила

2023-09-03 19:45 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +        <p className="text-font16 font-formular font-bold leading-[16px]">
видалила font-formular

2023-09-03 19:45 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +
ок

2023-09-03 19:45 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +import Icon from 'public/icons/close2.svg';
виправила

2023-09-03 19:45 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +                aria-label="Кнопка Закрити модальне вікно"
ок

2023-09-03 19:46 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +  children: PropTypes.node,
виправила

2023-09-04 07:52 UTC, BogdanGlazkov requested changes

2023-09-04 07:52 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +};
Треба додати можливість скролу, бо зараз відкривається так і не скролиться, не видно кнопку закриття https://prnt.sc/ZnLYT0TNWOxM

2023-09-04 07:52 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +};
На мобілці треба додати модалці можливість розширюватись до досягнення ширини екрану 480px
https://prnt.sc/JLsRRMtz3pZF

2023-09-04 10:27 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +};
ок, додала

2023-09-04 11:47 UTC, BogdanGlazkov requested changes

2023-09-04 11:47 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +                  className="text-bgColor block ml-auto mb-[24px] md:mb-[8px] xl:mb-[12px] w-[48px] h-[48px] transition duration-300 ease-out hover:text-accent"
transition прибрати

2023-09-04 11:47 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +};
Зараз модалка якось дуже низько розташована https://prnt.sc/A18ovPXo5ygE
Все за макетом, але на мобілці виглядає не дуже, думаю можна підняти

2023-09-04 11:47 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +                  className="text-bgColor block ml-auto mb-[24px] md:mb-[8px] xl:mb-[12px] w-[48px] h-[48px] transition duration-300 ease-out hover:text-accent"
focus додати (такий як і hover)

2023-09-04 11:50 UTC, BogdanGlazkov requested changes

2023-09-04 11:50 UTC, BogdanGlazkov commented on src/components/ConnectButton/ConnectButton.jsx
> +        className={`flex items-center gap-2 m-0 p-0 transition transform duration-300 ease-out hover:scale-[1.15] ${
Додати focus

2023-09-04 14:42 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +                  className="text-bgColor block ml-auto mb-[24px] md:mb-[8px] xl:mb-[12px] w-[48px] h-[48px] transition duration-300 ease-out hover:text-accent"
ок

2023-09-04 14:44 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +};
ок

2023-09-04 14:46 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +        className={`flex items-center gap-2 m-0 p-0 transition transform duration-300 ease-out hover:scale-[1.15] ${
додала

2023-09-04 15:47 UTC, BogdanGlazkov requested changes

2023-09-04 15:47 UTC, BogdanGlazkov commented on src/components/ConnectModal/ConnectModal.jsx
> +                  className="text-bgColor block ml-auto mb-[24px] md:mb-[8px] xl:mb-[12px] w-[48px] h-[48px] duration-300 ease-out focus:text-accent"
Де hover зник?

2023-09-04 15:52 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +                  className="text-bgColor block ml-auto mb-[24px] md:mb-[8px] xl:mb-[12px] w-[48px] h-[48px] duration-300 ease-out focus:text-accent"
виправила

2023-09-04 15:57 UTC, BogdanGlazkov approved these changes

2023-09-05 08:10 UTC, nadiakhoptiuk requested changes

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/components/ConnectButton/ConnectButton.jsx
> +import Icon from 'public/icons/connect.svg';
картинки, іконки, стилі імпортуємо в кінці

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/components/ConnectButton/ConnectButton.jsx
> +      {isOpen && (
краще робити відступи між блоками для читабельності

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/components/ConnectButton/ConnectButton.jsx
> +        <p className="text-font24 xl:text-font16 font-bold leading-[16px]">
в кнопку по семантиці вставляємо спан, а не абзац

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/components/ConnectButton/ConnectButton.jsx
> +      <button
при фокусі оверлей сходами, можна задати кнопці висоту як висота рядка тексту всередині

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/components/ConnectModal/ConnectModal.jsx
> +        <div className="fixed inset-0 bg-accent/75" aria-hidden="true">
backdrop-filter: blur(125px); не задано на бекдроп

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/components/ConnectModal/ConnectModal.jsx
> +                  aria-label="Закрити"
треба детальніше описати, кнопка закриття модального вікна

2023-09-05 08:10 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +        <ConnectButton color="accent" />
тільки в нас ця кнопочка буде не в герої, а в умовному блоці навбар, чи як назвемо

2023-09-05 09:47 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +import Icon from 'public/icons/connect.svg';
ок

2023-09-05 09:49 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +        <p className="text-font24 xl:text-font16 font-bold leading-[16px]">
виправила

2023-09-05 09:49 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +      {isOpen && (
ок

2023-09-05 09:52 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +                  aria-label="Закрити"
ок

2023-09-05 09:54 UTC, Nataly-Moskalenko commented on src/sections/Hero/Hero.jsx
> +        <ConnectButton color="accent" />
так, вона тут тимчасово, щоб потестіти модалку можна було

2023-09-05 09:57 UTC, Nataly-Moskalenko commented on src/components/ConnectModal/ConnectModal.jsx
> +        <div className="fixed inset-0 bg-accent/75" aria-hidden="true">
виправила

2023-09-05 11:00 UTC, Nataly-Moskalenko commented on src/components/ConnectButton/ConnectButton.jsx
> +      <button
виправила

2023-09-05 11:19 UTC, nadiakhoptiuk approved these changes

2023-09-05 11:19 UTC, merged