Feature/button consultation
SoftRyzen-internship/IM-CONSULTING pull request #30
Opened 2023-09-07 15:26 UTC by Nataly-Moskalenko

2023-09-07 15:56 UTC, BogdanGlazkov requested changes

2023-09-07 15:56 UTC, BogdanGlazkov commented on src/components/ButtonConsultation/ButtonConsultation.jsx
> +        className="flex gap-[8px] md:gap=[10px] py-[20px] bg-accent w-full md:w-[500px] justify-center items-center md:ml-auto"
md:gap=[10px] тут дефіс. Постав собі розширення Tailwind CSS IntelliSense у VSCode, буде підказувати

2023-09-07 15:56 UTC, BogdanGlazkov commented on src/components/ButtonConsultation/ButtonConsultation.jsx
> +        className="flex gap-[8px] md:gap=[10px] py-[20px] bg-accent w-full md:w-[500px] justify-center items-center md:ml-auto"
Перевірити падінги, letter-spacing

2023-09-08 10:20 UTC, Nataly-Moskalenko commented on src/components/ButtonConsultation/ButtonConsultation.jsx
> +        className="flex gap-[8px] md:gap=[10px] py-[20px] bg-accent w-full md:w-[500px] justify-center items-center md:ml-auto"
ок, за пораду з розширенням дякую!

2023-09-08 12:09 UTC, nadiakhoptiuk requested changes

2023-09-08 12:09 UTC, nadiakhoptiuk commented on src/components/ButtonConsultation/ButtonConsultation.jsx
> +        className="flex gap-[8px] md:gap-[10px] py-[16px] bg-accent w-full md:w-[500px] justify-center items-center md:ml-auto"
ефект ховера/фокуса додати як на інших кнопках (Програми)

2023-09-08 13:55 UTC, Nataly-Moskalenko commented on src/components/ButtonConsultation/ButtonConsultation.jsx
> +        className="flex gap-[8px] md:gap-[10px] py-[16px] bg-accent w-full md:w-[500px] justify-center items-center md:ml-auto"
додала

2023-09-08 15:28 UTC, nadiakhoptiuk approved these changes

2023-09-08 15:29 UTC, merged