Feature/accordion
SoftRyzen-internship/IM-CONSULTING pull request #31
Opened 2023-09-07 15:32 UTC by RomanPyryn

2023-09-08 08:06 UTC, nadiakhoptiuk requested changes

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +            <div
тут поставити умову 

```
{isActive ? (
              <div className="accordion-content-box-active"> 
весь вміст
</div>
            ) : (
              <div className="accordion-content-box"></div>
            )}
``` 
            
 `.accordion-content-box {
    @apply p-0 h-0 opacity-0 transition-all duration-300;
  }
  .accordion-content-box-active {
    @apply pt-6 pb-8 md:pt-9 md:pb-12 xl:pt-12 xl:pb-[60px] h-auto opacity-100 transition-all duration-300;
  }`
  
 другий дів буде порожній без падінгів, перший з вмістом і з падінгами, так позбуваємось зависання, а падінги анімуються  
стилі зручно писати прямо в коді

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +              <div className="accordion-content">
цей дів зайвий, флекс можна поставити на зовнішній (його батька)

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +                <ul className="accordion-content-list">
краще стилі писати зразу в коді, це зручно і при написанні коду, і при перевірці

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +                <div className="flex justify-end">
обгортка для кнопки зайва, кнопку можна зробити block і задати ml-auto як варіант

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +            <div
заголовок краще зробити кнопкою (по функціоналу), щоб можна було табати з клавіатури

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +              <h2 className="accordion-title">{item.title}</h2>
це у нас буде h3, а на секції стоятиме прихований через visually-hidden заголовок h2

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +                      <h3 className="accordion-subtitle">{subItem.subtitle}</h3>
h4 буде

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/sections/Test/Test.jsx
> +export const Test = () => {
можна одразу цю секцію перейменувати на ProgramInfo, щось таке

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/sections/Test/Test.jsx
> +      <Container>
сюди додати h2 прихований і прокинути пропсом рядок з назвою, мабуть у json вписати
+ типізувати його

2023-09-08 08:06 UTC, nadiakhoptiuk commented on src/styles/globals.css
> +  .accordion {
весь смак тейлвінда в тому, щоб писати ці стилі прямо в jsx

2023-09-08 09:32 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +            <div
Виправив

2023-09-08 09:34 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +              <div className="accordion-content">
Виправив

2023-09-08 09:34 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +                <ul className="accordion-content-list">
виправив

2023-09-08 10:33 UTC, RomanPyryn commented on src/sections/Test/Test.jsx
> +      <Container>
Який текст у h2 вписати?

2023-09-08 10:33 UTC, RomanPyryn commented on src/styles/globals.css
> +  .accordion {
виправив

2023-09-08 10:34 UTC, RomanPyryn commented on src/sections/Test/Test.jsx
> +export const Test = () => {
переіменував

2023-09-08 10:34 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +                      <h3 className="accordion-subtitle">{subItem.subtitle}</h3>
зробив

2023-09-08 10:34 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +              <h2 className="accordion-title">{item.title}</h2>
зробив

2023-09-08 10:34 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +            <div
переробив

2023-09-08 12:45 UTC, nadiakhoptiuk requested changes

2023-09-08 12:45 UTC, nadiakhoptiuk commented on src/sections/TrainingsInfo/TrainingsInfo.jsx
> +import { title, items } from '@/data/services/trainingsInfo.json';
Should not import the named export 'title' (imported as 'title') from default-exporting module (only default export is available soon)

імпортуй, будь ласка, дефолтним імпортом

2023-09-08 12:45 UTC, nadiakhoptiuk commented on src/sections/ConsultingInfo/ConsultingInfo.jsx
дуже гарно вийшло, але залишаємо лише одну секцію ProgramInfo, яка буде шаблоном
+ я писала про пропси для неї, якщо вийде їх додати без сторінок

2023-09-08 12:46 UTC, nadiakhoptiuk commented on src/sections/ConsultingInfo/ConsultingInfo.jsx
також додаємо скрол до верхньої частини акордеону

2023-09-08 15:45 UTC, nadiakhoptiuk requested changes

2023-09-08 15:45 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +                {/* <ButtonConsultation /> */}
кнопка уже є на деві

2023-09-08 15:54 UTC, nadiakhoptiuk requested changes

2023-09-08 15:54 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +              className={`cursor-pointer w-full pt-2 md:pt-3 border-t flex justify-between gap-4 xl:gap-[482px] transition duration-[750ms] ease-in ${
duration-300

2023-09-12 08:58 UTC, nadiakhoptiuk requested changes

2023-09-12 08:58 UTC, nadiakhoptiuk commented on src/components/Accordion/Accordion.jsx
> +// import { ButtonConsultation } from '../ButtonConsultation';
додати кнопку

2023-09-12 11:01 UTC, RomanPyryn commented on src/components/Accordion/Accordion.jsx
> +// import { ButtonConsultation } from '../ButtonConsultation';
додав

2023-09-12 12:11 UTC, nadiakhoptiuk approved these changes

2023-09-12 12:12 UTC, merged