Bugfix/form
SoftRyzen-internship/IM-CONSULTING pull request #32
Opened 2023-09-08 07:14 UTC by dianaforost

При відправці форми видаляються пробіли, після успішної відправки форми, модальне вікно закривається. кнопка неактивна при успішній відправці 3 сек, потім стає активною.

2023-09-08 15:44 UTC, nadiakhoptiuk requested changes

2023-09-08 15:44 UTC, nadiakhoptiuk commented on src/components/Form/Form.jsx
> +      formData.name = formData.name.trim();
ти можеш додати trim() у схему валідації перед усіма required, це буде оптимальніше

2023-09-08 16:42 UTC, dianaforost commented on src/components/Form/Form.jsx
> +      formData.name = formData.name.trim();
Дякую, виправлено!

2023-09-11 07:55 UTC, nadiakhoptiuk approved these changes

2023-09-11 07:57 UTC, merged