Feature/services hero
SoftRyzen-internship/IM-CONSULTING pull request #35
Opened 2023-09-09 15:58 UTC by dianaforost

2023-09-11 08:35 UTC, nadiakhoptiuk requested changes

2023-09-11 08:35 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col items-end w-[134px] md:w-auto xl:w-[500px]">
зайва обгортка

2023-09-11 08:35 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col w-[134px] md:w-[40%] xl:min-w-[476px] xl:absolute xl:right-[552px]">
зайва обгортка, стилі можна перенести на абзац, посунувши маржинами (авто)

2023-09-11 08:35 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col items-end max-w-[134px] md:max-w-[342px] xl:max-w-[500px]">
так само, зайва обгортка

2023-09-11 08:35 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +      <div className="flex justify-between md:justify-normal xl:justify-end md:items-center md:gap-[5%] xl:gap-[0] mb-[48px] md:mb-[164px] xl:mb-[182px] xl:h-[88px]">
якщо ми залишимо відступ зліва як на 320, то потрібно буде по-іншому ділити (на 2 діва, посередині буде границя між ними - як по фону)

тут на таблеті ти ставиш ширину на h1 і gap між ними, але логічніше і простіше задати двом дівами ширину і падінги, як варіант, щоб не вираховувати ось це все - ширину (яка навіть не збігається з текстом), гап

2023-09-11 08:35 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <h1 className="text-[20px] md:w-[322px] xl:w-[auto] xl:absolute xl:left-0 md:text-[48px] xl:text-[72px] text-accent leading-[24px] md:leading-[59px] xl:leading-[88px] tracking-[0.1em]">
на десктопі не по сітці: https://prnt.sc/um0yWdAgeRPD, можна не абсолютом, а релатівом змістити відносно себе, дивись як зручніше

2023-09-11 08:37 UTC, nadiakhoptiuk requested changes

2023-09-11 08:37 UTC, nadiakhoptiuk commented on src/sections/ServicesHero/ServicesHero.jsx
> +export const ServicesHero = ({ heroContent }) => {
тут буде інший пропс, не потрібно буде діставати Object.keys

2023-09-11 08:37 UTC, nadiakhoptiuk commented on src/data/services/coaching.json
> +  "coachingHero": {
структура (і ключі) у цих файлах повинні бути ідентичні, змінюються тільки назви.

в кожній шаблонній сторінці/секції ми достукуємось до одних і тих же ключів

2023-09-11 09:50 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col items-end w-[134px] md:w-auto xl:w-[500px]">
Виправлено

2023-09-11 09:50 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col w-[134px] md:w-[40%] xl:min-w-[476px] xl:absolute xl:right-[552px]">
Виправлено

2023-09-11 09:50 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col items-end max-w-[134px] md:max-w-[342px] xl:max-w-[500px]">
Виправлено

2023-09-11 09:54 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +      <div className="flex justify-between md:justify-normal xl:justify-end md:items-center md:gap-[5%] xl:gap-[0] mb-[48px] md:mb-[164px] xl:mb-[182px] xl:h-[88px]">
Переробила ніби правильно)

2023-09-11 09:54 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <h1 className="text-[20px] md:w-[322px] xl:w-[auto] xl:absolute xl:left-0 md:text-[48px] xl:text-[72px] text-accent leading-[24px] md:leading-[59px] xl:leading-[88px] tracking-[0.1em]">
Виправлено

2023-09-11 09:55 UTC, dianaforost commented on src/data/services/coaching.json
> +  "coachingHero": {
Виправлено

2023-09-11 11:07 UTC, dianaforost commented on src/sections/ServicesHero/ServicesHero.jsx
> +export const ServicesHero = ({ heroContent }) => {
Поки залишати так? Поки на всіх буде один бєкгрунд.

2023-09-11 13:44 UTC, nadiakhoptiuk requested changes

2023-09-11 13:44 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +          <p className="hero-description md:w-[100%] xl:min-w-[476px] xl:absolute xl:right-[552px] font-light text-white text-[12px] md:text-[20px] xl:text-[24px] leading-[15px] md:leading-[24px] xl:
xl:absolute дубляж

2023-09-11 13:44 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col gap-[129px] md:gap-[217px] min-w-[48%] md:min-w-[322px]">
замість 129 гап - justify-content: space-between;

2023-09-11 13:44 UTC, nadiakhoptiuk commented on src/sections/ServicesHero/ServicesHero.jsx
> +      } relative h-auto w-[100%] max-w-[100%]`}
потрібно фіксувати висоту секції, бо фон обрізає, голову.. (
релатів мабуть зайвий.
верхній і нижній падінги з контейнера перенести на секцію

2023-09-11 13:44 UTC, nadiakhoptiuk commented on src/data/services/trainings.json
> +    "text": "Створіть свій шлях до досягнення цілей у житті, карєрі та бізнесі"
апостроф у кар'єрі

2023-09-11 13:44 UTC, nadiakhoptiuk commented on src/sections/ServicesHero/ServicesHero.jsx
> +export const ServicesHero = ({ heroContent }) => {
як хочеш, потім переробимо

2023-09-11 14:13 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +          <p className="hero-description md:w-[100%] xl:min-w-[476px] xl:absolute xl:right-[552px] font-light text-white text-[12px] md:text-[20px] xl:text-[24px] leading-[15px] md:leading-[24px] xl:
Виправлено

2023-09-11 14:13 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +        <div className="flex flex-col gap-[129px] md:gap-[217px] min-w-[48%] md:min-w-[322px]">
Виправлено

2023-09-11 14:14 UTC, dianaforost commented on src/sections/ServicesHero/ServicesHero.jsx
> +      } relative h-auto w-[100%] max-w-[100%]`}
Виправлено. Стало краще, але не впевнена чи фіксована висота секції сильно допомогла.

2023-09-11 14:14 UTC, dianaforost commented on src/data/services/trainings.json
> +    "text": "Створіть свій шлях до досягнення цілей у житті, карєрі та бізнесі"
Виправлено

2023-09-12 09:15 UTC, nadiakhoptiuk requested changes

2023-09-12 09:15 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +      <div className="flex flex-row justify-center gap-[12px] md:gap-[31px] md:justify-between">
цей дів прибираєш, а стилі з нього повністю переносиш на контейнер у ServicesHero

2023-09-12 09:15 UTC, nadiakhoptiuk commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +          <p className="hero-description md:w-[100%] xl:min-w-[476px] xl:right-[552px] font-light text-white text-[12px] md:text-[20px] xl:text-[24px] leading-[15px] md:leading-[24px] xl:leading-[29p
xl:absolute xl:bottom-[203px] xl:right-[552px] прибрати, 

додати margin-top: auto 

і він статично собі розміститься там. де треба

2023-09-12 09:15 UTC, nadiakhoptiuk commented on src/sections/ServicesHero/ServicesHero.jsx
> +      <Container className="relative overflow-hidden">
на контейнер ще додати h-full

2023-09-12 09:26 UTC, dianaforost commented on src/sections/ServicesHero/ServicesHero.jsx
> +      <Container className="relative overflow-hidden">
Виправлено

2023-09-12 09:26 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +          <p className="hero-description md:w-[100%] xl:min-w-[476px] xl:right-[552px] font-light text-white text-[12px] md:text-[20px] xl:text-[24px] leading-[15px] md:leading-[24px] xl:leading-[29p
Виправлено

2023-09-12 09:26 UTC, dianaforost commented on src/components/ServicesHeroContent/ServicesHeroContent.jsx
> +      <div className="flex flex-row justify-center gap-[12px] md:gap-[31px] md:justify-between">
Виправлено

2023-09-12 12:50 UTC, nadiakhoptiuk approved these changes

2023-09-12 12:50 UTC, merged