Feature/partners
SoftRyzen-internship/IM-CONSULTING pull request #36
Opened 2023-09-10 09:28 UTC by Nataly-Moskalenko

Додано 2 залежності: "react-slick": "^0.29.0", "slick-carousel": "^1.8.1".

2023-09-11 09:14 UTC, BogdanGlazkov approved these changes

2023-09-12 09:40 UTC, nadiakhoptiuk requested changes

2023-09-12 09:40 UTC, nadiakhoptiuk commented on src/components/PartnersSwiper/PartnersSwiper.jsx
> +    <div className="partners-swiper">
div зайвий, цей клас можна задати через className на свайпер сам

і бажано, щоб на секції були падінги, бо виміряти розміри важко, щоб порівняти з дизайном, але якщо не вийде, то вже..

2023-09-12 10:36 UTC, Nataly-Moskalenko commented on src/components/PartnersSwiper/PartnersSwiper.jsx
> +    <div className="partners-swiper">
ок

2023-09-12 11:43 UTC, nadiakhoptiuk approved these changes

2023-09-12 11:44 UTC, merged