Feature/pages navbar
SoftRyzen-internship/IM-CONSULTING pull request #39
Opened 2023-09-11 12:10 UTC by BogdanGlazkov

2023-09-13 09:05 UTC, nadiakhoptiuk requested changes

2023-09-13 09:05 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +      <NavBar isDark={isDark} />
і візуально, і по структурі проєкту, навбар геть не у хедері, а в лейауті
можна використати контекст

2023-09-13 20:44 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +      <NavBar isDark={isDark} />
Переніс назад у layout

2023-09-14 08:38 UTC, nadiakhoptiuk requested changes

2023-09-14 08:38 UTC, nadiakhoptiuk commented on src/layout/NavBar/NavBar.jsx
> +import { routes } from '../../../routes';
написати без макаронів

2023-09-14 08:38 UTC, nadiakhoptiuk commented on src/sections/Hero/Hero.jsx
> +        {' '}
прибери {' '}

2023-09-14 08:58 UTC, nadiakhoptiuk requested changes

2023-09-14 08:58 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +import { routes } from '../../../routes';
макарони

2023-09-14 08:58 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +      className={`${
ці всі класи треба винести кудись в окрему функцію або юзефект в цьому компоненті

2023-09-14 08:58 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +  const closeMenu = () => setIsMenuOpen(false);
ця функція зайва, прекрасно працює на лого і в меню  handleMenuToggle

2023-09-14 09:07 UTC, BogdanGlazkov commented on src/layout/NavBar/NavBar.jsx
> +import { routes } from '../../../routes';
+)

2023-09-14 09:08 UTC, BogdanGlazkov commented on src/sections/Hero/Hero.jsx
> +        {' '}
+

2023-09-14 09:10 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +import { routes } from '../../../routes';
+

2023-09-14 09:55 UTC, BogdanGlazkov commented on src/layout/Header/Header.jsx
> +      className={`${
+

2023-09-14 11:06 UTC, nadiakhoptiuk approved these changes

2023-09-14 11:10 UTC, merged