readme add
SoftRyzen-internship/IM-CONSULTING pull request #42
Opened 2023-09-12 09:44 UTC by sergio-nezhigay

не впевнений що саме це писати в readme

2023-09-12 09:59 UTC, BogdanGlazkov requested changes

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +![Зображення сайту](/images/omg-hero.jpg)
Виправити шлях, бо зображення не відображається https://prnt.sc/qqck3fBGPthp

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +- Отримання зворотного зв'язку від клієнтів. 📞
зворотнього

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +зворотного зв'язку від клієнтів. 🌟
зворотнього

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +## ✏️ Редагування (Editing)
Думаю нам не треба, щоб хтось потім редагував цей сайт. Цей розділ можна прибрати

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +  E --> P[Сторінка коучінг]
Зробити текст більш темним, бо зараз не читабельно https://prnt.sc/WaLeAZopllV3

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +- CSS framework: Tailwind 🎨
Можна додати більше технологій (з файлу package.json)

2023-09-12 09:59 UTC, BogdanGlazkov commented on README.md
> +Дякуємо за вашу участь! 🙌
Додати в кінці контакти компанії SoftRyzen

2023-09-12 11:03 UTC, sergio-nezhigay commented
виправив, запушив

2023-09-12 11:16 UTC, BogdanGlazkov requested changes

2023-09-12 11:16 UTC, BogdanGlazkov commented on README.md
> +- CSS framework: Tailwind 🎨
Tailwind повторюється

2023-09-12 11:16 UTC, BogdanGlazkov commented on README.md
> +- CSS framework: Tailwind 🎨
Забагато технологій теж не ок, думаю можна прибрати деякі ненайважливіші, такі як @formspree/react, @hookform/resolvers, autoprefixer, eslint-config-next, react-dom

2023-09-12 11:16 UTC, BogdanGlazkov commented on README.md
> +- CSS framework: Tailwind 🎨
Додати nodemailer

2023-09-12 11:16 UTC, BogdanGlazkov commented on README.md
> +- CSS framework: Tailwind 🎨
Додати Backend: json

2023-09-12 11:16 UTC, BogdanGlazkov commented on README.md
> +📧 **Email:** [services@softryzen.com](mailto:services@softryzen.com)
Додати сайт)

2023-09-12 11:55 UTC, BogdanGlazkov approved these changes

2023-09-13 08:43 UTC, nadiakhoptiuk requested changes

2023-09-13 08:43 UTC, nadiakhoptiuk commented on README.md
> +- Environment variables: 🔐 `dotenv`
ми не використовуємо dotenv в next

2023-09-13 08:43 UTC, nadiakhoptiuk commented on README.md
> +- Notification component: 📢 `react-toastify`
у нас немає цієї ліби

2023-09-13 08:43 UTC, nadiakhoptiuk commented on README.md
> +- Email sending: 📧 nodemailer
+ телеграм апі

2023-09-13 08:43 UTC, nadiakhoptiuk commented on README.md
> +- Веб-ресурс доступний для будь-якого підключення до Інтернету. 📱🌐
для будь-якого девайсу, що має підключення до Інтернету

2023-09-13 08:43 UTC, nadiakhoptiuk commented on README.md
> +3. Налаштування змінних середовища: Створіть файл `.env.local` у кореневій папці
у нас .env

2023-09-13 11:00 UTC, nadiakhoptiuk approved these changes

2023-09-13 11:03 UTC, merged