Feature/meta
SoftRyzen-internship/IM-CONSULTING pull request #57
Opened 2023-09-14 07:20 UTC by sergio-nezhigay

2023-09-14 09:03 UTC, BogdanGlazkov requested changes

2023-09-14 09:03 UTC, BogdanGlazkov commented on src/app/layout.jsx
> +export const TITLE = 'Im Consulting';
Напевно IM Consulting

2023-09-14 09:03 UTC, BogdanGlazkov commented on src/components/RefContext/RefContext.jsx
> +};
Де ми використовуємо цей компонент?

2023-09-14 09:19 UTC, BogdanGlazkov approved these changes

2023-09-14 10:13 UTC, nadiakhoptiuk requested changes

2023-09-14 10:13 UTC, nadiakhoptiuk commented on public/icon-192x192.png
в папці паблік треба зробити окрему папку meta, туди помістити всі іконки і т.д.

тільки favicon.ico і opengraph - в корені app

2023-09-14 10:13 UTC, nadiakhoptiuk commented on src/app/layout.jsx
> +  title: TITLE,
додати metadataBase (потрібно для опенграф)

2023-09-14 10:13 UTC, nadiakhoptiuk commented on src/app/layout.jsx
> +    type: 'website',
додати manifest

2023-09-14 10:13 UTC, nadiakhoptiuk commented on src/app/layout.jsx
> +  },
twitter: {
      card: 'summary_large_image',
    },

2023-09-14 10:13 UTC, nadiakhoptiuk commented on src/app/[services]/page.jsx
> +  const services = params.services;
деструктуризувати services в аргументах функції

витягнути файли за допомогою утиліти на кшалт getPage

2023-09-14 10:13 UTC, nadiakhoptiuk commented on src/app/robots.txt
> +User-Agent: *
наче цей тег не додався (локально)

2023-09-14 16:44 UTC, BogdanGlazkov commented on src/app/layout.jsx
> +export const TITLE = 'Im Consulting';
IM це аббревіатура (ім'я та прізвище автора)

2023-09-14 17:10 UTC, sergio-nezhigay commented on src/app/layout.jsx
> +export const TITLE = 'Im Consulting';
а я думав це фраза "I'm consulting= I am consulting"

2023-09-15 07:41 UTC, nadiakhoptiuk requested changes

2023-09-15 07:41 UTC, nadiakhoptiuk commented on src/app/[services]/page.jsx
> +export default async function ServicesPage1({ params: { services } }) {
тут випадкова зміна, мабуть

2023-09-15 07:41 UTC, nadiakhoptiuk commented on src/data/services/seo.coaching.json
> +  "title": "Послуги коучінга в компанії IM Consulting",
давай тут напишемо за макетом: коучИнг

2023-09-15 07:41 UTC, nadiakhoptiuk commented on src/data/services/seo.coaching.json
> +  "description": "Послуги коучінга в IM Consulting. Командний, лайф-коучінг, кар'єрний коучінг та коучінг керівників"
давай тут напишемо за макетом: коучИнг всюди виправити

Послуги коучингу

2023-09-15 07:41 UTC, nadiakhoptiuk commented on src/data/services/seo.consulting.json
> +  "title": "Послуги консалтінга в компанії IM Consulting",
Послуги консалтингу в компанії IM Consulting

Консалтинг усюди

2023-09-15 07:41 UTC, nadiakhoptiuk commented on src/data/services/seo.trainings.json
> +  "title": "Послуги тренінга в компанії IM Consulting",
Тренінги в компанії IM Consulting

2023-09-15 07:41 UTC, nadiakhoptiuk commented on src/data/services/seo.trainings.json
> +  "description": "Послуги тренінга в IM Consulting. Керівникам, торговим представникам, аптечний візит, візит до лікаря, менеджерам з продажу, продавцям-консультантам, провізорам. Тренування стратегі
Тренінги в компанії IM Consulting

2023-09-15 08:24 UTC, nadiakhoptiuk requested changes

2023-09-15 08:24 UTC, nadiakhoptiuk commented on src/app/layout.jsx
> +    <>
тут зайвий батьківський тег фрагмента

2023-09-15 08:24 UTC, nadiakhoptiuk commented on src/data/services/seo.coaching.json
> +  "description": "Послуги коучингу в IM Consulting. Командний, лайф-коучінг, кар'єрний коучінг та коучінг керівників"
лайф-коучінг кар'єрний коучінг та коучінг керівників - всюди змінити

2023-09-15 08:30 UTC, nadiakhoptiuk approved these changes

2023-09-15 08:33 UTC, merged