feature/socials
SoftRyzen-internship/IM-CONSULTING pull request #6
Opened 2023-09-02 20:52 UTC by Anastasia-front

add icons, create Socials component and put it in the header

2023-09-03 11:30 UTC, BogdanGlazkov requested changes

2023-09-03 11:30 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +
Відступ між зовнішніми та внутрішніми імпортами

2023-09-03 11:30 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +  component: PropTypes.string,
isRequired

2023-09-03 11:30 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +    footer: 'text-bgColor hover:text-accent',
Там де hover, додаємо і focus - такий самий

2023-09-03 11:30 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +    footer: 'text-bgColor hover:text-accent',
Ще треба додати плавний перехід, наприклад duration-300

2023-09-03 11:30 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +    </>
Якщо повертаємо один елемент, додатково огортати його не потрібно

2023-09-03 12:28 UTC, nadiakhoptiuk requested changes

2023-09-03 12:28 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +            aria-label="Viber"
можна вказати, що це лінк (на обидва)

2023-09-03 13:26 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +            aria-label="Viber"
виправила

2023-09-03 13:26 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +    </>
так, дякую, забула прибрати фрагмент

2023-09-03 13:27 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +  component: PropTypes.string,
виправила

2023-09-03 13:27 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +
виправила

2023-09-03 13:28 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +    footer: 'text-bgColor hover:text-accent',
виправила

2023-09-03 20:02 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +
Зайві відступи теж не потрібні. Зовнішні імпорти разом (причому PropTypes в кінці, бо використовується в самому низу сторінки), потім відступ, потім внутрішні імпорти

2023-09-03 20:02 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +            aria-label="Viber"
Мається на увазі aria-label="Link to Viber"?

2023-09-03 20:06 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +      'text-black hover:text-white focus:text-white transition duration-300',
transition тут вказувати не потрібно

2023-09-03 20:06 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +      'text-accent hover:text-white focus:text-white transition duration-300',
transition тут вказувати не потрібно

2023-09-03 20:06 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +      'text-bgColor hover:text-accent focus:text-accent transition duration-300',
transition тут вказувати не потрібно

2023-09-03 20:06 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +            aria-label="Viber"
Зовнішні посилання через тег а, там все правильно було

2023-09-03 20:08 UTC, BogdanGlazkov requested changes

2023-09-03 20:08 UTC, BogdanGlazkov commented on src/components/Socials/Socials.jsx
> +          aria-label="Telegram"
aria-label="Link to Telegram"

2023-09-04 13:04 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +            aria-label="Viber"
внесла зміни

2023-09-04 13:06 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +
зрозуміла, тут виправила, далі всі імпорти буду правильно групувати

2023-09-04 13:07 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +      'text-accent hover:text-white focus:text-white transition duration-300',
видалила

2023-09-04 13:07 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +      'text-bgColor hover:text-accent focus:text-accent transition duration-300',
видалила

2023-09-04 13:07 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +          aria-label="Telegram"
видалила

2023-09-04 15:08 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +          aria-label="Telegram"
ще чекаю актуальних посилань на соціальні мережі замовника

2023-09-05 08:14 UTC, BogdanGlazkov approved these changes

2023-09-05 09:45 UTC, nadiakhoptiuk requested changes

2023-09-05 09:45 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +    <ul className={listClass[component]}>
в ідеалі мепнути масив із data (із aria-label, href), додавши іконки.

2023-09-06 09:14 UTC, nadiakhoptiuk requested changes

2023-09-06 09:14 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +  component: PropTypes.string.isRequired,
тут краще описати масив рядків, які мають приходити, "header" ...

2023-09-06 09:14 UTC, nadiakhoptiuk commented on src/data/home/socials.js
зроби json і просто перенеси сюди socials масив, а з data прибрати можна

2023-09-06 11:13 UTC, Anastasia-front commented on src/components/Socials/Socials.jsx
> +  component: PropTypes.string.isRequired,
виправила

2023-09-06 11:15 UTC, Anastasia-front commented on src/data/home/socials.js
зробила

2023-09-06 11:28 UTC, nadiakhoptiuk approved these changes

2023-09-06 11:31 UTC, merged