feature/logo
SoftRyzen-internship/IM-CONSULTING pull request #7
Opened 2023-09-02 20:54 UTC by Anastasia-front

add logo.svg, create Logo component and put it in the header  

cannot add hover color, tried many different options - need help

2023-09-03 11:56 UTC, BogdanGlazkov requested changes

2023-09-03 11:56 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +import { routes } from 'routes';
Відступом відокремити зовнішні імпорти від внутрішніх

2023-09-03 11:56 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +      className="flex items-center px-[7px] py-[6px] w-[48px] h-[48px]"
На десктопі розміри більші

2023-09-03 11:56 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +import LogoIcon from 'public/icons/logo.svg';
Іконку треба або оптимізувати, щоб вона змінювала колір, прибрати fill, розміри, id, або замінити на png картинку та підміняти її при ховері

2023-09-03 11:56 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +      className="flex items-center px-[7px] py-[6px] w-[48px] h-[48px]"
Додати hover, focus та перехід (напр. duration-300)

2023-09-05 10:41 UTC, Anastasia-front commented on src/components/Logo/Logo.jsx
> +import LogoIcon from 'public/icons/logo.svg';
зробила

2023-09-05 10:42 UTC, Anastasia-front commented on src/components/Logo/Logo.jsx
> +import { routes } from 'routes';
зробила

2023-09-05 10:42 UTC, Anastasia-front commented on src/components/Logo/Logo.jsx
> +      className="flex items-center px-[7px] py-[6px] w-[48px] h-[48px]"
зробила

2023-09-05 13:28 UTC, BogdanGlazkov requested changes

2023-09-05 13:28 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +      text-white hover:text-accent focus:text-accent duration-300"
Додати transition

2023-09-05 15:43 UTC, Anastasia-front commented on src/components/Logo/Logo.jsx
> +      text-white hover:text-accent focus:text-accent duration-300"
на іконках соц мереж я додавала, ти написав видалити - тут за твоєю логікою зробила вже без нього
але додала тут тепер transition
то за яким принципом його додавати?

2023-09-05 15:45 UTC, Anastasia-front commented on src/components/Logo/Logo.jsx
> +      text-white hover:text-accent focus:text-accent duration-300"
зрозуміла - Надія за це вдень написала, що transition має бути всюди де є переходи

2023-09-05 17:36 UTC, BogdanGlazkov approved these changes

2023-09-05 17:38 UTC, BogdanGlazkov commented on src/components/Logo/Logo.jsx
> +      text-white hover:text-accent focus:text-accent duration-300"
Так, тепер скрізь додаєм. Вимоги як макет дизайнера, постійно щось може помінятися)

2023-09-05 17:49 UTC, Anastasia-front commented on src/components/Logo/Logo.jsx
> +      text-white hover:text-accent focus:text-accent duration-300"
при фокусі виходить залипання кольору - забула за це вдень написати
так само й у іконках соціальних мереж
так має бути?

2023-09-06 08:34 UTC, nadiakhoptiuk approved these changes

2023-09-06 08:34 UTC, merged