creates loader
SoftRyzen-internship/IM-CONSULTING pull request #8
Opened 2023-09-03 08:55 UTC by Nataly-Moskalenko

2023-09-03 11:00 UTC, BogdanGlazkov requested changes

2023-09-03 11:00 UTC, BogdanGlazkov commented on src/components/Loader/Loader.jsx
> +    </>
Якщо повертаємо 1 компонент, додатково огортати його не потрібно

2023-09-03 19:40 UTC, Nataly-Moskalenko commented on src/components/Loader/Loader.jsx
> +    </>
ок, виправила

2023-09-03 19:50 UTC, BogdanGlazkov approved these changes

2023-09-04 07:15 UTC, nadiakhoptiuk approved these changes

2023-09-04 07:16 UTC, merged